### ISSUE TITLE
BUG: Inline math collides with adjacent text

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python.myst#117]
@DrDrij @AakashGfude There are cases of `inline` text colliding with adjacent text. Perhaps this can be fixed with more padding around `inline` math in `quantecon-book-theme` (or a different issue?)

https://quantecon.github.io/lecture-python.myst/ge_arrow.html#preferences-and-endowments

This is `high-priority` as I'd like to fix it before we `switch` to the `live` site.

**Comment by mmcky** [comment]
This may actually be another `safari` issue as `chrome` on @jstac machine looks good.

**Comment by DrDrij** [comment]
@mmcky Could you please attach a screenshot? Tested in Safari on my machine:

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/5886045/112786193-6f842e00-90a1-11eb-977e-89a0d27c3c63.png">

**Comment by AakashGfude** [comment]
@DrDrij I think its that small overlap of 
<img width="174" alt="Screen Shot 2021-03-29 at 3 30 29 pm" src="https://user-images.githubusercontent.com/6542997/112787171-b2470580-90a3-11eb-9a73-afb143db3bf6.png">

I investigated and it felt like a mathjax issue in rendering. It would if you can verify this once. If it is the case, then we can open an issue in mahjax?

**Comment by mmcky** [comment]
It's mainly associated with `superscipts` and `subscripts` colliding with text
<img width="1011" alt="Screen Shot 2021-03-31 at 12 49 59 pm" src="https://user-images.githubusercontent.com/8263752/113078850-a7b17b00-921f-11eb-8fd5-c6284ab18d8a.png">

This is from `linear_models`

**Comment by DrDrij** [comment]
Thanks guys. Working on a solution here, [PR](https://github.com/QuantEcon/quantecon-book-theme/pull/96)
