### ISSUE TITLE
Text not compatible with contrast toggle. 

### ISSUE THREAD

**Issue by jhilto** [QuantEcon/lecture-python.myst#134]
Changing to the dark theme using the "change contrast" button on the toolbar renders elements of the text unreadable. Compare these two screenshots from Lecture 28. The equations disappear and the code become less contrasted. 

<img width="829" alt="Screen Shot 2021-04-20 at 3 12 08 PM" src="https://user-images.githubusercontent.com/25337478/115451346-12385400-a1eb-11eb-8839-52e274c73627.png">
<img width="821" alt="Screen Shot 2021-04-20 at 3 12 47 PM" src="https://user-images.githubusercontent.com/25337478/115451335-0ea4cd00-a1eb-11eb-9d0b-37ef85157398.png">

**Comment by mmcky** [comment]
thanks @jhilto -- sorry for the delay on this. 

@AakashGfude @DrDrij would this be something we can look at in the theme?

**Comment by mmcky** [comment]
actually @jhilto this has been fixed 🎉 in a previous theme updated

https://python.quantecon.org/cake_eating_problem.html
