### ISSUE TITLE
[lecture_comparison]view_source_file_bottom_directs_to_wrong_site

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#15]
Good morning @mmcky . 

I noticed that the bottom ``view_source_file`` on the top-right-side of the homepage and of each lecture does not direct us to the right GitHub source website (i.e., this repo).

For example, please look at the screenshots of the [homepage](https://quantecon.github.io/lecture-python.myst/intro.html) and lecture [geom_series](https://quantecon.github.io/lecture-python.myst/geom_series.html), where I labelled the bottom with red lines.

![Screen Shot 2020-12-12 at 7 20 17 am](https://user-images.githubusercontent.com/53931041/101951127-96ca0300-3c4a-11eb-8e54-82776465a90d.png)
![Screen Shot 2020-12-12 at 7 20 40 am](https://user-images.githubusercontent.com/53931041/101951132-992c5d00-3c4a-11eb-8fa9-f66f7c6e9e1a.png)

Btw, I really love those awesome new features, like increasing/decreasing the font size and changing the contrast (night mode).

**Comment by mmcky** [comment]
Thanks @shlff -- this is fixed by: https://github.com/QuantEcon/quantecon-book-theme/pull/77
