### ISSUE TITLE
[short_path] Missing figures

### ISSUE THREAD

**Issue by oyamad** [QuantEcon/lecture-python.myst#160]
Figures are not displayed in https://python.quantecon.org/short_path.html

See for example this link: https://python.quantecon.org/_static/lecture_specific/short_path/graph.png

**Comment by jstac** [comment]
Thanks @oyamad !

@mmcky Could you please prioritize fixing this?

**Comment by mmcky** [comment]
thanks @oyamad for reporting this. 

@AakashGfude for some reason the `gh-pages` version of `_images` has some empty `png` files? Does `sphinx` resize these images as they get migrated to `_images` folder. The local build seems OK (with images) showing for this lecture so I might need to do a `local` sync for gh-pages until we understand why this is happening.

**Comment by mmcky** [comment]
@oyamad @jstac I have uploaded a manual build. 

For some reason the `build` via `github actions` is writing `png` files that are empty (but the correct size). Perhaps this is something coming down from `sphinx`. We will investigate further -- but for now we will use `local builds` on all projects to publish updates to `gh-pages`

**Note:** these types of assets are cached by the browser so you will need to do a cache reset to restore the images or (give it time to expire).

**Comment by jstac** [comment]
Many thanks @mmcky .  Please let me know how your investigation goes.

**Comment by oyamad** [comment]
Thanks @mmcky, figures are now displayed. Closing this issue.

Just a remark, as far as I checked, missing figures occurred only in Shortest Paths. For example, figures were already displayed in Schelling.

**Comment by mmcky** [comment]
thanks @oyamad -- agree -- it appears to affecting just some select images.

**Comment by mmcky** [comment]
@AakashGfude I am at least able to replicate this: 

https://github.com/QuantEcon/lecture-python.myst/pull/161

**Comment by mmcky** [comment]
@AakashGfude I think I figured this one out. 

https://github.com/QuantEcon/lecture-python.myst/pull/162
