### ISSUE TITLE
Use `np.full`?

### ISSUE THREAD

**Issue by oyamad** [QuantEcon/lecture-python.myst#165]
In several pieces of code, an array of a constant value is created by something like

```py
Q = np.ones((num_nodes, num_nodes))
Q = Q * np.inf
```

This can be simplified with [`np.full`](https://numpy.org/doc/stable/reference/generated/numpy.full.html):

```py
Q = np.full((num_nodes, num_nodes), np.inf)
```

**Comment by mmcky** [comment]
thanks @oyamad I am all for this.

@shlff would you have time to go through the lectures and make a PR?

**Comment by jstac** [comment]
Thanks @oyamad , I didn't know about `np.full`. 

 @shlff please go ahead when you have time.  In this and other lectures, you can search for `np.ones` and see if it's being used in the pattern that @oyamad mentioned (creation of a constant vector).

**Comment by shlff** [comment]
Thanks @jstac , @oyamad and @mmcky . 

I went through all lectures in ``lecture-python.myst`` and find similar patterns in the following lectures:
- [career](https://python.quantecon.org/career.html): ``v = np.ones((cw.grid_size, cw.grid_size)) * 100``
- [geom_series](https://python.quantecon.org/geom_series.html): ``f_2 = np.ones(T_max+1)*infinite_lease(g, r, x_0)``
- [inventory_dynamics](https://python.quantecon.org/inventory_dynamics.html): ``X = np.ones(num_firms) * x_init``
- [lake_model](https://python.quantecon.org/lake_model.html): ``V = np.ones(len(mcm.w_vec))  # Initial guess of V``
- [linear_algebra](https://python.quantecon.org/linear_algebra.html): ``B = np.ones((3, 3))`` and ``y = np.ones((2, 1))``
- [lqcontrol](https://python.quantecon.org/lqcontrol.html): ``income_r = np.ones(T-K) * s``
- [markov_asset](https://python.quantecon.org/markov_asset.html): ``n = 5`` ``P = 0.0125 * np.ones((n, n))
- [mccall_correlated](https://python.quantecon.org/mccall_correlated.html): ``f_init = np.log(js.c) * np.ones(len(js.z_grid))``
- [multi_hyper](https://python.quantecon.org/multi_hyper.html): ``Σ = np.ones((c, c)) * n * (N - n) / (N - 1) / N ** 2``
- [multivariate_normal](https://python.quantecon.org/multivariate_normal.html): ``μ_IQ = np.ones(n+1) * μθ`` and ``μb = np.ones(T) * 𝛼0``
- [odu](https://python.quantecon.org/odu.html): ``e = np.ones((N, T+1))`` and `` π = np.ones((N, T+1)) * 1e-3``
- [short_path](https://python.quantecon.org/short_path.html): ``Q = np.ones((num_nodes, num_nodes))`` and ``Q = Q * np.inf`` (**This one is exactly what @oyamad mentioned.**)
- [time_series_with_matrices](https://python.quantecon.org/time_series_with_matrices.html): ``b = np.ones(T) * 𝛼0`` and ``b_steady = np.ones(T) * 𝛼0``
- [wealth_dynamics](https://python.quantecon.org/wealth_dynamics.html): ``ψ_0 = np.ones(num_households) * wdy.y_mean`` and ``ψ_0 = np.ones(num_households) * wdy.y_mean`` and ``ψ_0 = np.ones(num_households) * wdy.y_mean``

I am not really sure which one is better: ``Q = np.ones((num_nodes, num_nodes)) * np.inf`` or ``Q = np.full((num_nodes, num_nodes), np.inf)``. 

But maybe we can implement some simple experiments to see compare the speed and stability (e.g., under ``numba``) for these two cases?

**Comment by jstac** [comment]
Thanks @shlff .

A few of these do not fit the pattern @oyamad identified: using `np.ones` to create an array and then multiplying it by a constant to create a constant vector.

Can you please cut down this list to just those examples?

(Once we have a list fitting this pattern, we will change them all to use `np.full`, since dealing with this pattern is the purpose of that function.)

**Comment by shlff** [comment]
Thanks @jstac . Please find the updated list above.

Looking forward to your comments.

**Comment by jstac** [comment]
Thanks @shlff , good work.  That list is correct so please proceed.

**Comment by shlff** [comment]
Thanks @jstac . In the next step I will create a PR to replace all patterns in that list with ``np.full``, suggested by @oyamad .

**Comment by oyamad** [comment]
There are a few more:

* [ ] inventory_dynamics.md
* [ ] lake_model.md
* [ ] complex_and_trig.md
* [ ] multivariate_normal.md
* [ ] samuelson.md
  Use [np.full_like](https://numpy.org/doc/stable/reference/generated/numpy.full_like.html).
* [ ] [markov_asset.md](https://github.com/QuantEcon/lecture-python.myst/blame/6e7ff58935700e9ee8e514b8fffd4408ecfacbed/lectures/markov_asset.md#L926)

  ```py
  P += np.diag(0.95 - 0.0125 * np.ones(5))
  ```

  This does not seem to be very clever. It should be, for example,

  ```py
  P[range(n), range(n)] += 1 - P.sum(1)
  ```

  or

  ```py
  P[np.diag_indices(n)] += 1 - P.sum(1)
  ```

**Comment by shlff** [comment]
Thanks @oyamad . I will check the pattern through the lectures you mentioned above and create another PR to modify it.
