### ISSUE TITLE
[short_path] `sum_costs` in `print_best_path`

### ISSUE THREAD

**Issue by oyamad** [QuantEcon/lecture-python.myst#166]
Computing `sum_costs` again in `print_best_path` is redundant: it has already been computed as `J[0]`.

If this is intentional, then a comment should be given, demonstrating that `sum_costs` is indeed equal to `J[0]`.

**Comment by mmcky** [comment]
@shlff would you have time to review this and make a PR?

**Comment by jstac** [comment]
Many thanks for the report @oyamad .

I will handle this one @shlff .  (Thanks @mmcky )

**Comment by jstac** [comment]
This is a good point @oyamad .  Somehow I didn't think of it ;-)

I've adjusted the lecture accordingly.  Thanks again.
