### ISSUE TITLE
[lecture_comparison]some_links_in_new_version_lectures_direct_to_older_version_lectures

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#17]
Hi @mmcky , @AakashGfude, and @jstac 

I noticed an issue in the new-myst-version [lecture-python](https://quantecon.github.io/lecture-python.myst/intro.html) that 
- some links (external ref) in new-version lectures direct us back to our old-version lectures instead of the corresponding parts in the new lectures.

For example, the two external reference, ``(see for example this lecture and this lecture)``, after the following sentence in lecture [lq_control](https://quantecon.github.io/lecture-python.myst/lqcontrol.html#overview):
- ``Classical formulations of linear control and linear filtering problems make use of similar matrix decompositions``

or please see the following screenshot with red lines:
![Screen Shot 2020-12-17 at 4 35 46 pm](https://user-images.githubusercontent.com/53931041/102448299-f595df00-4085-11eb-9076-a009aab31f09.png)

I am afraid that it is not a single mistake. 

Do you have some ways to detect them or want me to detect and correct them when I do the comparison job?

**Comment by mmcky** [comment]
@shlff I think this is likely because the links used are to https://python.quantecon.org/<lecture> which is showing the current `live` site. This will be the future link when these lectures get updated. Can you confirm that is the case in the source file. Thanks.

**Comment by shlff** [comment]
Thanks @mmcky . 

I checked the source file and these links are indeed directing back to lectures of our website: https://python.quantecon.org/.

Please also see the screenshot below:
![Screen Shot 2020-12-21 at 11 44 28 am](https://user-images.githubusercontent.com/53931041/102728908-62f58880-4382-11eb-9c05-f0ea62510500.png)

**Comment by mmcky** [comment]
Thanks @shlff this won't cause issues once these sources are defined as `python.quantecon.org` links. So I am closing this issue.
