### ISSUE TITLE
[lecture_comparison]_missing_links_to_previous/next_lectures_at_the_bottom

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#19]
Good morning @mmcky , I noticed that in the ``MYST`` lectures,
- we do not have links to previous/next lectures

e.g., in lecture [geom_series](https://quantecon.github.io/lecture-python.myst/geom_series.html) (left: ``MYST``, right: ``RST``),
![Screen Shot 2021-01-02 at 8 26 51 am](https://user-images.githubusercontent.com/53931041/103446484-4fc4b000-4cd4-11eb-94b5-2eec638a2b3c.png)

I know we have an expansion content once we click the bottom ``Tables of Contents`` on the left top side of ``MYST`` versions, where we can click any lecture in the ``basic`` part, but do you think it is a good idea to add links to previous/next lectures at the bottom of the new versions?

**Comment by mmcky** [comment]
Thanks @shlff the `next` and `previous` buttons are not part of the current theme. Instead we opted for users to navigate using the `toc` (top left) of the page. We think this will be intuitive enough.

**Comment by mmcky** [comment]
Closing this as I don't think this needs to be tracked. If we want to incorporate into the theme - we can do so later on.
