### ISSUE TITLE
[lecture_comparison] Issues in footnote notations

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#20]
Good morning, @mmcky , I find two issues/differences in footnote notations between ``MYST`` and ``RST`` websites (left: ``MYST``, right: ``RST``):
- the footnote citations in the lecture contexts are without brackets and are not treated as superscript, e.g. in [linear_algebra](https://quantecon.github.io/lecture-python.myst/linear_algebra.html#id2),
![Screen Shot 2021-01-02 at 8 50 18 am](https://user-images.githubusercontent.com/53931041/103446786-9bc52400-4cd7-11eb-868a-57e367c3170e.png)

- for the footnotes at the bottom, there is no subtitle ``Footnotes`` and the footnotes start from a different line from its numbering:
![Screen Shot 2021-01-02 at 8 53 48 am](https://user-images.githubusercontent.com/53931041/103446833-1b52f300-4cd8-11eb-8279-613894fd53ae.png)

Do you think we should modify the footnotes' appearance in the ``MYST``?

**Comment by mmcky** [comment]
Nice pickup @shlff I think this needs to be improved upon. (cc: @DrDrij)

This is also related to https://github.com/QuantEcon/quantecon-book-theme/issues/76

**Comment by shlff** [comment]
Thanks @mmcky . I checked that this issue has not been solved yet.

![Uploading Screen Shot 2021-03-11 at 11.20.06 am.png…]()

**Comment by mmcky** [comment]
thanks @shlff -- I have current focused on `high priority` tags. We will focus on this as an improvement.

**Comment by shlff** [comment]
Thanks @mmcky and @DrDrij 's beautiful work (cc @jstac ). 

This is no longer an issue and I will close it.
