### ISSUE TITLE
A question about the lecture "Samuelson Multiplier Accelerator"

### ISSUE THREAD

**Issue by jxx87** [QuantEcon/lecture-python.myst#207]
Hello,
In the lecture "Samuelson Multiplier Accelerator," a snippet of codes is copied below:

```
def plot_simulation(self, ts_length=100, stationary=True):
    # Set distribution parameters equal to their stationary values for simulation
    if stationary == True:
        try:
        self.μ_x, self.μ_y, self.σ_x, self.σ_y = self.stationary_distributions()
        self.μ_0 = self.μ_y
        self.Σ_0 = self.σ_y
      ...
    x, y = self.simulate(ts_length)
```
I wonder why:
```
self.μ_0 = self.μ_y
self.Σ_0 = self.σ_y
```
Instead of:
```
self.μ_0 = self.μ_x
self.Σ_0 = self.σ_x
```
Since my understanding is that when later using simulate(), x_0 first draws from N (μ_0, Σ_0). So shouldn't x_0 draws from N(μ_x, σ_x) instead of N(μ_y, σ_y)?

**Comment by shizejin** [comment]
Hello,

Thank you very much for your spotting of this! You are correct, and we have fixed in a new PR #210, and there are some other changes that you could take a look if interested.

Thanks again!
