### ISSUE TITLE
[lecture_comparison]_uncentering_generating/inserted_plots/figures_in_myst

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#21]
Hi @mmcky (cc: @jstac), I find 
- whatever it is a plot/figure generated by code or inserted directly, the plot/figure in ``MYST`` is located in the left rather than in the center like what we can see in ``RST`` versions.

For example, in lecture [heavy_tails](https://quantecon.github.io/lecture-python.myst/heavy_tails.html) (left: ``MYST``, right: ``RST``), for inserted plots/figures,
![Screen Shot 2021-01-02 at 10 12 42 am](https://user-images.githubusercontent.com/53931041/103447728-37a85d00-4ce3-11eb-9e97-dba47aefa2bb.png)

for generated plots/figures,
![Screen Shot 2021-01-02 at 10 13 15 am](https://user-images.githubusercontent.com/53931041/103447734-48f16980-4ce3-11eb-91bc-c91f41685c47.png)

Do you think it is an issue?

**Comment by mmcky** [comment]
thanks @shlff -- this looks like a `quantecon-book-theme` issue

**Comment by shlff** [comment]
Thanks @mmcky and @DrDrij . I can confirm that this issue has been solved.

![Screen Shot 2021-03-11 at 11 17 59 am](https://user-images.githubusercontent.com/53931041/110716546-7fa3ad00-825b-11eb-8540-e7910d73f201.png)

![Screen Shot 2021-03-11 at 11 18 14 am](https://user-images.githubusercontent.com/53931041/110716554-83cfca80-825b-11eb-8fe7-0b172fe4b260.png)
