### ISSUE TITLE
Error in Geometric series lecture?

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-python.myst#212]
Thanks to Richard Rivero for this:

I’m not sure you have the right Taylor series for G^{T+1} about g=0, somewhere down the page. 

https://python.quantecon.org/geom_series.html 

I would think it would be more something like:

![image](https://user-images.githubusercontent.com/3887684/157805065-246e540c-5270-4b35-9753-257635c1b2a5.png)

**Comment by Smit-create** [comment]
Yeah, we can verify that using `sympy`:
```py
>>> from sympy import series
>>> from sympy.abc import t, g
>>> f = (1 + g)**(t + 1)
>>> series(f, g)
1 + g*(t + 1) + g**2*t*(t + 1)/2 + g**3*t*(t - 1)*(t + 1)/6 + g**4*t*(t - 2)*(t - 1)*(t + 1)/24 + g**5*t*(t - 3)*(t - 2)*(t - 1)*(t + 1)/120 + O(g**6)
```
