### ISSUE TITLE
[lecture_comparison]_no_labels_``In``&``Out``_for_code_cells&its_outputs_in_myst

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#22]
Hi @mmcky , I find 
- there are no labels ``In``&``Out`` for code cells and its outputs in ``MYST`` versions, but we do have those labels in ``RST`` versions.

For example, in lecture [heavy_tails](https://quantecon.github.io/lecture-python.myst/heavy_tails.html) (left: ``MYST``, right: ``RST``), 

![Screen Shot 2021-01-02 at 10 28 37 am](https://user-images.githubusercontent.com/53931041/103447876-527bd100-4ce5-11eb-8be2-2ed87774730c.png)

Do you think it is an issue?

**Comment by mmcky** [comment]
This would be changed in `quantecon-book-theme` 

They could be added if we want them back.

**Comment by mmcky** [comment]
Closing this as tracked in https://github.com/QuantEcon/quantecon-book-theme/issues/83
