### ISSUE TITLE
[lecture_comparison][multivariate_normal] A whole section is missing

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#24]
Good morning @mmcky , I find that
- a whole section ``Filtering Foundations`` is missing in ``MYST`` of [8_multivariate_normal](https://quantecon.github.io/lecture-python.myst/multivariate_normal.html) (left: ``MYST``, right: ``RST``)

![Screen Shot 2021-01-03 at 10 28 12 am](https://user-images.githubusercontent.com/53931041/103468567-76efb000-4dae-11eb-94bb-c1d20939f905.png)

**Comment by mmcky** [comment]
I think this is likely just a timing issue of the migration

Tom committed this content after the migration: https://github.com/QuantEcon/lecture-python/commit/4b82e74501b880f239442e46309605dd247019e7#diff-289a509772ff83c9ccfa87761af14e945463c072836550793038f5a897175934 

- [ ] bring in updated `multivariate_normal` using `sphinx-tomyst` from `lecture-python`

**Comment by mmcky** [comment]
@shlff I have updated #16 with the latest sources so I hope this issue can be closed now. Would you mind to check and close (if ok). Thanks.

**Comment by shlff** [comment]
Thanks @mmcky . I checked the preview from #16 and can confirm that this issue has been fixed by #16 .

I will close this issue.
