### ISSUE TITLE
Missing arguments in McCall with Fitted Value Function Iteration

### ISSUE THREAD

**Issue by Okroshiashvili** [QuantEcon/lecture-python.myst#246]
The **McCallModelContinuous** class constructor is missing μ and σ if we want to control distribution of wages inside the class. If we don't want that, then inside **update** method μ and σ are redundant and removing them will make code runnable and will not throw exception.

[Here is the lecture link](https://github.com/QuantEcon/lecture-python.myst/blob/main/lectures/mccall_fitted_vfi.md)

**Comment by jstac** [comment]
@Okroshiashvili Many thanks for pointing that out.   @shlff, do you have time to review this and fix as necessary?

**Comment by shlff** [comment]
Sure thanks @jstac and @Okroshiashvili . I've had a look at the code, and I agree with @Okroshiashvili .

Here is a PR that fixes the code without affecting the results of current remaining code.

**Comment by jstac** [comment]
Fixed in #248
