### ISSUE TITLE
[lecture_comparison] Broken internal reference

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#25]
Dear @mmcky , I find some internal references in the ``MYST`` are broken.

For example, in lecture [optgrowth_fast](https://quantecon.github.io/lecture-python.myst/optgrowth_fast.html#id2) (left: ``MYST``. right: ``RST``),

![Screen Shot 2021-01-03 at 10 56 56 am](https://user-images.githubusercontent.com/53931041/103468948-9be62200-4db2-11eb-9c27-f7d2a0d9619a.png)

in lecture [34_ifp](https://quantecon.github.io/lecture-python.myst/ifp.html),

![Screen Shot 2021-01-03 at 11 02 41 am](https://user-images.githubusercontent.com/53931041/103469008-73aaf300-4db3-11eb-85d0-954d3e77afee.png)

The same issue exists in the following lectures (keep updating):
- [31_optgrowth_fast](https://quantecon.github.io/lecture-python.myst/optgrowth_fast.html#id2)
- [34_ifp](https://quantecon.github.io/lecture-python.myst/ifp.html)

**Comment by mmcky** [comment]
Thanks @shlff I suspect this was due to those lectures not executing properly. Would you mind to check #16 preview build and see if this is still an issue.

**Comment by shlff** [comment]
Thanks @mmcky . I checked #16's preview build and find the issue in both lectures [31_optgrowth_fast](https://5ff580ff1bec79c49f4be5b2--nostalgic-wright-5fa355.netlify.app/optgrowth_fast.html#id3) and [34_ifp](https://5ff580ff1bec79c49f4be5b2--nostalgic-wright-5fa355.netlify.app/ifp.html) still exists.

**Comment by mmcky** [comment]
thanks for checking @shlff -- I have looked at the source and the references were split across two lines

**Comment by mmcky** [comment]
re comments in PR this issue is now fixed pending merge of the `manual-adjustment` PR's
