### ISSUE TITLE
[lecture_comparison] Images need review for size on Jupyter Book

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#26]
Hi @mmcky , I find that some inserted figures/pictures in ``MYST`` are oversized!

For example, in lecture [wald_friedman](https://quantecon.github.io/lecture-python.myst/wald_friedman.html#intuition) (left: ``MYST``, right: ``RST``)
![Screen Shot 2021-01-03 at 12 13 13 pm](https://user-images.githubusercontent.com/53931041/103469773-1c118500-4dbd-11eb-954f-df766ece5d78.png)

in lecture [finite_markov](https://quantecon.github.io/lecture-python.myst/finite_markov.html),
![Screen Shot 2021-01-03 at 12 16 08 pm](https://user-images.githubusercontent.com/53931041/103469805-9215ec00-4dbd-11eb-8bfc-e4bbfea34a89.png)

**Comment by mmcky** [comment]
Thanks @shlff agreed -- this will be an issue across the spectrum. 

I have found the following settings to work pretty well and are located in the [QuantEcon Style Guide -- Figure Sizes](https://quantecon.github.io/QuantEcon.manual/writing/styleguide.html#figure-sizes) for matplotlib generated items. 

Would you mind reviewing each lecture and submitting a PR with some suggested updates?

**Comment by shlff** [comment]
> Thanks @shlff agreed -- this will be an issue across the spectrum.
> 
> I have found the following settings to work pretty well and are located in the [QuantEcon Style Guide -- Figure Sizes](https://quantecon.github.io/QuantEcon.manual/writing/styleguide.html#figure-sizes) for matplotlib generated items.
> 
> Would you mind reviewing each lecture and submitting a PR with some suggested updates?

Thanks, @mmcky . This [QE Operation Manual](https://quantecon.github.io/QuantEcon.manual/writing/styleguide.html#figure-sizes) designs standards, which is very helpful for lectures development and exactly what I want to do before. Thank you!

However, I find the figure size settings mentioned by this guide is for code-generating plots only, but not for inserted figures. Do you think we should add some standards for inserted plots as well?

I'd love to review these lectures, experiment with different figure sizes and give my comments on them via PR.

**Comment by mmcky** [comment]
> but not for inserted figures. Do you think we should add some standards for inserted plots as well?

@shlff this is hard to do as the source image may vary in size. So this is largely down to `authors` to adjust accordingly. I would recommend using `:scale:` to fill ~0.5-0.7 width of the page in many circumstances

>  experiment with different figure sizes and give my comments on them via PR

Thanks. This experimentation will need to be done in the `myst` repository as it handles images differently to the `jupinx` approach to image scalling.

**Comment by shlff** [comment]
Thanks @mmcky . I will create PR to fix this issue in the ``myst`` repo after you finish migrating lectures here.

**Comment by mmcky** [comment]
thanks @shlff you can proceed on a `lecture` by `lecture` basis with suggestions for new image sizes now. When you open a PR add `[{{ lecture name}}]` in the tile and add the tag `manual-change` so we don't merge it into `main` yet until `rst` is frozen.

**Comment by mmcky** [comment]
I think https://github.com/QuantEcon/lecture-python.myst/pull/108 addresses this issue
