### ISSUE TITLE
Add A New Lecture on Fast Fixed Point Computation Using Gradient Methods

### ISSUE THREAD

**Issue by HumphreyYang** [QuantEcon/lecture-python.myst#265]
Add a new lecture on fast fixed point computation using gradient methods based on https://github.com/QuantEcon/cbc_workshops/blob/main/day_2/solow_fixed_points.ipynb and potentially discuss the multidimensional newton's method for a multi-sector model.

**Comment by jstac** [comment]
Combine the above with https://github.com/QuantEcon/cbc_workshops/blob/main/day_4/equilib_nd.ipynb
