### ISSUE TITLE
[lecture_comparison] Numba Deprecation Warnings

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#27]
Hi @mmcky (cc: @jstac ), I find an issue about ``NumbaDepreciationWarning`` in some ``MYST`` lectures,
- caused by imports ``from numba import jitclass``

For example, in lecture [wald_friedman](https://quantecon.github.io/lecture-python.myst/wald_friedman.html#intuition) (left: ``MYST``, right: ``RST``),

![Screen Shot 2021-01-03 at 12 21 54 pm](https://user-images.githubusercontent.com/53931041/103470033-fd14f200-4dc0-11eb-8e4b-7777fefe3d64.png)

I also find this issue in some other lectures. 

As you explained previously, we should replace this import with ``from numba.experimental import jitclass``.

Do you want to create some PRs in ``lecture-python`` repo (https://github.com/QuantEcon/lecture-python) to replace these imports and solve this issue?

**Comment by mmcky** [comment]
Thanks @shlff that would be great -- please go ahead and update these via PRs. Would you mind to list the lecture level PR's here so that I can then cross check this issue is resolved once we bring the latest files over from `lecture-python`.

**Comment by shlff** [comment]
Thanks @mmcky . Should I submit PRs in this repo?

**Comment by mmcky** [comment]
If the fix can be done before next week then the `rst` repo is the best place for this update.

**Comment by shlff** [comment]
Thanks @mmcky . I fix this issue here: https://github.com/QuantEcon/lecture-python/pull/343
