### ISSUE TITLE
Move Solutions below the Corresponding Exercises

### ISSUE THREAD

**Issue by HumphreyYang** [QuantEcon/lecture-python.myst#270]
This issue is set up to maintain the format consistency across the three lectures.

**Comment by HumphreyYang** [comment]
- [] Move solutions
- [] Fix some obvious deprecations along the way.

**Comment by HumphreyYang** [comment]
Hi @jstac and @mmcky, 

It seems to me that the exercise for [lecture on bayesian and frequentist interpretation](https://python.quantecon.org/prob_meaning.html#pm_ex2) is a little bit messy. Would you like me to create a separate issue and PR to tidy things up a little?

Also, I think we could write our own hypothesis testing and coverage interval sections instead of embedding a video.

Please kindly let me know what is your opinion on this.

Many thanks!

**Comment by jstac** [comment]
Hi Humphrey, 

> It seems to me that the exercise for [lecture on bayesian and frequentist interpretation](https://python.quantecon.org/prob_meaning.html#pm_ex2) is a little bit messy. Would you like me to create a separate issue and PR to tidy things up a little?

Yes, it would be good to break this long, multi-part exercise up into multiple questions with their own solutions.  All help is appreciated!

Regarding the vids, Tom Sargent wrote this lecture and I imagine he would like to keep those videos there (CC @thomassargent30).
