### ISSUE TITLE
[ar1_bayes] Issue with PyMC

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python.myst#275]
Current `cache` run shows an issue with `SciPy`

```
[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/usr/share/miniconda3/envs/quantecon/lib/python3.9/site-packages/scipy-1.7.3.dist-info/METADATA'
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/miniconda3/envs/quantecon/lib/python3.9/site-packages/scipy-1.7.3.dist-info/METADATA'
```

@AakashGfude @HumphreyYang not sure how this is possible as the `environment` hasn't changed recently. Open to ideas?

**Comment by mmcky** [comment]
@HumphreyYang I upgraded to use `anaconda=2022.10` which has just been released which fixed the `SciPy` issue but produced another issue in pymc. 

```
ContextualVersionConflict[0m: (arviz 0.12.1 (/usr/share/miniconda3/envs/quantecon/lib/python3.9/site-packages), Requirement.parse('arviz>=0.13.0'), {'pymc'})
ContextualVersionConflict: (arviz 0.12.1 (/usr/share/miniconda3/envs/quantecon/lib/python3.9/site-packages), Requirement.parse('arviz>=0.13.0'), {'pymc'})
```

@HumphreyYang would you be able to look into this and let me know if I need to pin pymc perhaps?

**Comment by HumphreyYang** [comment]
Hi @mmcky,

I think we have an outdated `arviz` version in` environment.yml`: `arviz==0.12.1`. Maybe we should update it to `arviz>=0.13.0`
