### ISSUE TITLE
[lecture_comparison] An issue for both MyST and RST Versions

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#28]
Hi @mmcky (cc: @jstac ), I find an issue existing in both [MYST](https://quantecon.github.io/lecture-python.myst/navy_captain.html) and [RST](https://python.quantecon.org/navy_captain.html) versions of lecture [41_navy_captain]:
- the numbering ``2.`` in a list is compiled as ``1``, please see the following (left: ``MYST``, right:``RST``)

![Screen Shot 2021-01-04 at 9 23 54 am](https://user-images.githubusercontent.com/53931041/103490347-589db900-4e6f-11eb-81e5-057844a12a38.png)

I checked the source ``RST`` file, please find:

![Screen Shot 2021-01-04 at 9 30 20 am](https://user-images.githubusercontent.com/53931041/103490389-8682fd80-4e6f-11eb-96b6-9530dd8545c4.png)

Similar issue also exists in:
- [markov_asset](https://quantecon.github.io/lecture-python.myst/markov_asset.html)

![Screen Shot 2021-01-04 at 12 57 39 pm](https://user-images.githubusercontent.com/53931041/103494859-a96fda80-4e8c-11eb-9fb8-ecadf8215b81.png)

**Comment by mmcky** [comment]
Thanks @shlff I suspect this is because the `math` directive is not indented to be inline with the `list item`. You could try that on `lecture-python` via PR
