### ISSUE TITLE
[lecture_comparison][harrison_kreps] Markdown Tables are Broken in MyST

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#29]
Hi @mmcky , I noticed that in lecture [harrison_kreps](https://quantecon.github.io/lecture-python.myst/harrison_kreps.html),
- all tables written using ``markdown`` are broken (left: ``MYST``, right: ``RST``)

For example, please see the following:
![Screen Shot 2021-01-04 at 1 03 22 pm](https://user-images.githubusercontent.com/53931041/103495000-4d598600-4e8d-11eb-943d-95f4b5e09ba4.png)

And also in this lecture,
![Screen Shot 2021-01-06 at 4 02 40 pm](https://user-images.githubusercontent.com/53931041/103731181-a580bb80-5038-11eb-8102-fd1b47cdac28.png)

**Comment by mmcky** [comment]
thanks @shlff 

This is related to https://github.com/executablebooks/sphinx-tomyst/issues/90

**Comment by mmcky** [comment]
@shlff we don't have many tables so we may manually fix these rather than wait for implementation in `sphinx-tomyst`. Do you know of any other `tables`?

**Comment by shlff** [comment]
Thanks @mmcky . The two tables in lecture [harrison_kreps](https://quantecon.github.io/lecture-python.myst/harrison_kreps.html) are the only two broken in all these ``MYST`` lectures.

**Comment by mmcky** [comment]
thanks @shlff will be fixed by https://github.com/QuantEcon/lecture-python.myst/pull/30
