### ISSUE TITLE
Question about 9.15. Matrix Representation of Some Bivariate Distributions

### ISSUE THREAD

**Issue by dmitrymailk** [QuantEcon/lecture-python.myst#305]
Thank you a lot for the book. I found it very practical and insightful.

I have several questions about [9.15. Matrix Representation of Some Bivariate Distributions](https://python.quantecon.org/prob_matrix.html#matrix-representation-of-some-bivariate-distributions) part.

full code
```python
# specify parameters
xs = np.array([0, 1])
ys = np.array([10, 20])
f = np.array([[0.3, 0.2], [0.1, 0.4]])
f_cum = np.cumsum(f)

# draw random numbers
p = np.random.rand(1_000_000)
x = np.vstack([xs[1]*np.ones(p.shape), ys[1]*np.ones(p.shape)])
# map to the bivariate distribution

x[0, p < f_cum[2]] = xs[1]
x[1, p < f_cum[2]] = ys[0]

x[0, p < f_cum[1]] = xs[0]
x[1, p < f_cum[1]] = ys[1]

x[0, p < f_cum[0]] = xs[0]
x[1, p < f_cum[0]] = ys[0]
print(x)
```

1. I don't understand why `f_cum` is calculated in this way. I think it is [joint CDF](https://www.probabilitycourse.com/chapter5/5_1_2_joint_cdf.php) but it is computed slightly different.
```python
f = np.array([[0.3, 0.2], [0.1, 0.4]])
f_cum = np.cumsum(f)
# f_cum will be [0.3, 0.5, 0.6, 1.0] 
```
2. Therefore I don't understand next lines
```python
x[0, p < f_cum[2]] = xs[1]
x[1, p < f_cum[2]] = ys[0]
```
Why do we assign to the first line `xs[1]` where p less than `f_cum[2]`?

**Comment by jstac** [comment]
@dmitrymailk , many thanks for this report!  

Also noting the deprecation warning in that lecture (search for "retina").

@HumphreyYang or @Smit-create , do you have time to look into this?  If not let me know and I'll take a look.

**Comment by HumphreyYang** [comment]
Hi @dmitrymailk, 

Thanks for the issue. This part of the code is generating the samples to test whether it conforms with the theoretical distribution.

Recall that p are samples drawn uniformly from $[0, 1)$

So the code below will progressively map these values to the bivariate distribution. In this case,`f_cum` set the interval for which $x$ and $y$ that sample should be mapped to:

```
# Case 1: xs[1], ys[1], 0.6 <= p < 1
x = np.vstack([xs[1]*np.ones(p.shape), ys[1]*np.ones(p.shape)])

# At this stage all x are set to case 1

# Case 2: xs[1], ys[0], 0.5 <= p < 0.6
x[0, p < f_cum[2]] = xs[1]
x[1, p < f_cum[2]] = ys[0]

# At this stage all sample with 0.6 <= p < 1 are set to case 1 and 
# all samples with 0 <= p < 0.6 are set to case 2

# Case 3: xs[0], ys[1], 0.3 <= p < 0.5
x[0, p < f_cum[1]] = xs[0]
x[1, p < f_cum[1]] = ys[1]

# At this stage all sample with 0.6 <= p < 1 are set to case 1 and 
# all samples with 0.5 <= p < 0.6 are set to case 2
# all samples with  0 <= p < 0.5 are set to case 3

# Case 4: xs[0], ys[0]], 0 <= p < 0.3
x[0, p < f_cum[0]] = xs[0]
x[1, p < f_cum[0]] = ys[0]

# At this stage all sample with 0.6 <= p < 1 are set to case 1 and 
# all samples with 0.5 <= p < 0.6 are set to case 2
# all samples with 0.3 <= p < 0.5 are set to case 3
# all samples with  0 <= p < 0.3 are set to case 3
# and this is what we want
```

You can print the output between each update to see how `x[0]` and `x[1]` are updated according to the values of `p`.

Let me know if there is anything I can further explain :)

> @jstac: Also noting the deprecation warning in that lecture (search for "retina")

I will update the line in a separate PR and refer to this issue.

**Comment by jstac** [comment]
Thanks @HumphreyYang .

To summarize, you believe the code is OK?  (I haven't read it carefully yet.)

Do you think it needs further clarification?

**Comment by HumphreyYang** [comment]
> Thanks @HumphreyYang .
> 
> To summarize, you believe the code is OK? (I haven't read it carefully yet.)
> 
> Do you think it needs further clarification?

I think the code is OK, but it will benefit from more comments so readers can figure this out more quickly. However, the drawback of adding more comments is to make this already lengthy lecture longer. To keep the lecture simple, I would say we leave it as it is now.

**Comment by jstac** [comment]
Thanks @HumphreyYang 

@dmitrymailk , do you agree (bearing in mind that we try to keep lectures brief, conditional on sufficient clarity)?

**Comment by thomassargent30** [comment]
Dear Humphrey, Thanks for looking at this. I agree with your preference to
keep things short. There is already a lot in this lecture.  The machinery
is quite simple but instructive too.

Tom

**Comment by dmitrymailk** [comment]
Sorry for the long response. You answer helped me a lot. Thank you again for this great lectures. I think everything is fine.
