### ISSUE TITLE
[lecture_comparison][rational_expectations] \argmax Issue

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#31]
Dear @mmcky , I find another issue:
- ``\argmax`` is not compiled in an equation of lecture [rational_expectations](https://quantecon.github.io/lecture-python.myst/rational_expectations.html)

Please see the following (left: ``MYST``, right: ``RST``)
![Screen Shot 2021-01-06 at 3 58 42 pm](https://user-images.githubusercontent.com/53931041/103731610-a9f9a400-5039-11eb-8b31-6c1fa378ba91.png)

**Comment by mmcky** [comment]
grr -- not that issue again. `\argmax` is my nemisis :-). Thanks @shlff -- it's a `mathjax` configuration issue.

**Comment by mmcky** [comment]
This is fixed in #35 waiting for merge until `rst` is frozen.
