### ISSUE TITLE
[mccall_correlated] Standard deviation

### ISSUE THREAD

**Issue by oyamad** [QuantEcon/lecture-python.myst#312]
I often get confused with standard deviation/variance myself, but is this what was meant?

```
z_sd = np.sqrt(σ / (1 - ρ**2))
```
(In `JobSearch` in `mccall_correlated.md`:
https://github.com/QuantEcon/lecture-python.myst/blame/main/lectures/mccall_correlated.md#L210)

Is it `np.sqrt(σ**2 / (1 - ρ**2))` (i.e., `σ / np.sqrt(1 - ρ**2)`)?

**Comment by jstac** [comment]
Hi @oyamad , that looks wrong, many thanks for reporting.

@HumphreyYang , could you please review and put in a PR if a change is required.

**Comment by HumphreyYang** [comment]
Hi @oyamad,

Many thanks for spotting this error. I have double-checked the deviation and will create a PR to fix this.
