### ISSUE TITLE
[jax] Very slow compilation time in wealth_dynamics

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python.myst#317]
The cache is reporting a very slow compilation time for one of our `jax` requests on [190](https://github.com/QuantEcon/lecture-python.myst/actions/runs/4238029946/jobs/7364713704#step:7:190)

```bash
Executing: /__w/lecture-python.myst/lecture-python.myst/lectures/wealth_dynamics.md
external/org_tensorflow/tensorflow/compiler/xla/service/slow_operation_alarm.cc:65] 
********************************
[Compiling module jit_wealth_time_series_for_loop_jax] Very slow compile?  If you want to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results.
```

**Comment by mmcky** [comment]
@Smit-create are you reviewing `jax`? Would this be something you could look into?

**Comment by Smit-create** [comment]
Thanks, Matt.

I think the issue is with the new JAX version. I'll look into the reason for slow compilation.

**Comment by mmcky** [comment]
Even with `numpyro` installed we get the same message as well

```
Executing: /__w/lecture-python.myst/lecture-python.myst/lectures/wealth_dynamics.md
2023-02-22 03:36:21.137289: E external/org_tensorflow/tensorflow/compiler/xla/service/slow_operation_alarm.cc:65] 
********************************
[Compiling module jit_wealth_time_series_for_loop_jax] Very slow compile?  If you want to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results.
********************************
```

**Comment by jstac** [comment]
@mmcky , notice the following error message on the lecture itself: No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)

Do you know why it didn't find a GPU on this run?

**Comment by mmcky** [comment]
hey @jstac 👍 -- not sure yet -- other lectures seem to be finding it. I suspect the `jit` compilation step through `xla` is failing and it is falling back to `cpu`? Need to find a bit of time to dig into this one.

**Comment by Smit-create** [comment]
Is this failing with version `0.4.4`? I'll try to reproduce using the same version on colab GPU and see if I can find the bug.

**Comment by Smit-create** [comment]
I see we have the same issue on colab GPU too.

**Comment by Smit-create** [comment]
We have the same issue with exercise 30.4 of https://python.quantecon.org/kesten_processes.html. JAX isn't able to find the GPU. I'll debug more into this.

**Comment by Smit-create** [comment]
Ah, the issue is with this line: `!pip install --upgrade "jax[CPU]"`
If we are running on a GPU, we should upgrade using the following:
```
pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```

I think this should fix this. I'll raise a PR to test this. We can also remove the pin in this case.

**Comment by HumphreyYang** [comment]
I cancelled the [workflow](https://github.com/QuantEcon/lecture-python.myst/actions/runs/4258553977/jobs/7409936882) given it is taking more than 2 hours. I think we may need to manually cancel workflows or change CI before this is fixed :)

**Comment by jstac** [comment]
Thanks for your thoughts @Smit-create .  

> Ah, the issue is with this line: !pip install --upgrade "jax[CPU]"

The reason we have this is to meet the following objective: Anyone who downloads one of our lectures can run it without error, with zero changes, provided that they have the latest version of Anaconda installed.

But yes, it seems to be causing problems.  

@mmcky @HumphreyYang @thomassargent30 and I just discussed the possiblity of creating a completely separate lecture series focused on JAX + GPU to avoid these problems.
