### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by rosemm** [QuantEcon/lecture-python.myst#320]
Thank you for creating and sharing such wonderful content! I'd love to adapt some of your work for another project I'm working on, but I want to be sure to respect your wishes regarding attribution etc. I don't see a license file for this repo; do you have guidelines for sharing and reuse (perhaps one of the standard licenses at https://creativecommons.org/ would be a good fit)?

**Comment by jstac** [comment]
Hi @rosemm , thanks for the kind words :-)

The licence is hard to find: it's at the very bottom of https://python.quantecon.org/intro.html

Hopefully that's what you are looking for --- please let us know if not.

Perhaps we should add this to the repo @mmcky ?

**Comment by rosemm** [comment]
Thank you, that’s exactly what I was looking for! I’m sorry I didn’t notice it at the bottom of the page — I assumed there would be a license file in the repo, my bad! 
And thanks again for your great work on this project. What a valuable resource!
