### ISSUE TITLE
Fix Long Run Time (bayes_nonconj)

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python.myst#323]
It is currently taking the cache almost 3 hours to run this lecture set (from scratch). 

There are a number of issues reported by tensor flow such as:

```
/__w/lecture-python.myst/lecture-python.myst/lectures/wealth_dynamics.md: Executing notebook using local CWD [mystnb]
2023-03-22 01:10:05.558920: E external/org_tensorflow/tensorflow/compiler/xla/service/slow_operation_alarm.cc:65] 
********************************
[Compiling module jit_wealth_time_series_for_loop_jax] Very slow compile?  If you want to file a bug, run with envvar XLA_FLAGS=--=/tmp/foo and attach the results.
********************************
```

which suggests `jax` isn't running as it should again. 

- [x] once `quantecon` gpu machine is up and running we should test the lectures and `jax` on the `3080` to benchmark and diagnose what is going on.

**Comment by mmcky** [comment]
@HumphreyYang it looks like the `bayes_nonconj` maybe uninstalling `jax` due to the following

```
# install dependencies
!pip install numpyro pyro-ppl torch jax
```

It looks like torch is reinstalling all the `Cuda` infrastructure which may mean `jax` isn't running as it should and could explain the long run time. 

Not urgent but would you be able to:

1. Compare local runtime of this lecture to the web version
2. See if we can minimise the installs here so that `Cuda` libraries are not reinstalled.

**Comment by mmcky** [comment]
See output

```
An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.
```

**Comment by HumphreyYang** [comment]
Many thanks @mmcky, I will look into these options.

**Comment by HumphreyYang** [comment]
Hi @mmcky,

I tested this locally and on Colab. it still runs for around 30 mins. It takes around 1 minute for each MCMC and SVI simulation.

I think it is expected as the size of the simulation is quite large and MCMC is quite slow.
