### ISSUE TITLE
Remove heavy tailed distributions lecture from this site

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-python.myst#336]
The lecture `heavy_tails.md` is being moved to the undergraduate series and needs to be cut from this lecture series when the undergraduate series goes live.

**Comment by jstac** [comment]
@HumphreyYang , can you please provide a PR for @mmcky ?

**Comment by HumphreyYang** [comment]
Hi @jstac, this one needs some careful treatment as many lectures are linked to it. I just learnt [a small trick](https://docs.readthedocs.io/en/stable/guides/intersphinx.html) from @mmcky. I will have a try here.
