### ISSUE TITLE
Add a discussion for local installs / beyond Jupyter

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-python.myst#337]
Setting up a coding environment beyond Jupyter.

Discuss code editors, IPython, git, etc.

**Comment by HumphreyYang** [comment]
Hi @jstac, should we close this one as it is overlapping with https://github.com/QuantEcon/lecture-python-programming.myst/issues/279 ?

**Comment by jstac** [comment]
Thanks @HumphreyYang
