### ISSUE TITLE
Remove JAX material from Newton lecture

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-python.myst#339]
Regarding https://python.quantecon.org/newton_method.html

Summary: this lecture contains JAX material that is now redundant, since we cover the same material in the JAX lecture series.

TODO

- Remove everything from "A High-Dimensional..."
- In two good case, first do manual Newton via the derivatives calculated by hand in https://python.quantecon.org/newton_method.html#adding-gradient-information
- Then use a SciPy root finder, discuss the difference
- Remove JAX imports

**Comment by jstac** [comment]
@HengchengZhang @HumphreyYang @mmcky 

This is urgent, since we are going live with the JAX lectures.

**Comment by HumphreyYang** [comment]
Hi @jstac, 

I can take this issue and put together a PR within this week if there is still time.

**Comment by HengchengZhang** [comment]
Thanks Humphrey,

I can help you if needed.
________________________________

**Comment by jstac** [comment]
Thanks @HumphreyYang , much appreciated.  This week is fine.
