### ISSUE TITLE
Discuss the failure of ergodic theory and its implications

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#358]
Thanks @oyamad, for the discussion in #355 . I move our discussion there to this issue. 

The ergodic theory states a perfect benchmark, but I think it could also be very important to consider the failure of the ergodic theory and its implications on modelling non-ergodic phenomena in economics/finance.

Given that the whole lecture [lake model](https://python.quantecon.org/lake_model.html) relies on the assumptions of irreducibility (``(lambda, alpha) > (0, 0)``) and aperiodicity (``(lambda, alpha) neq (1, 1)``),

I propose that we can probably extend the discussion a bit to mention the non-ergodic cases for the lake model,
- ``(lambda, alpha) = (0, 0)``
- ``(lambda, alpha) = (0, 1)``
- ``(lambda, alpha) = (1, 0)``.

It is an excellent idea to simplify the steady state computation (proposed by #169) but it could also be important to mention that it cannot handle some of the nonergodic case.

Furthermore, we could possibly discuss the failure of ergodic theory and implications in the finite Markov chain lectures, [intro](https://intro.quantecon.org/markov_chains_II.html) or [intermediate](https://python.quantecon.org/finite_markov.html) (cc @jstac ), similar to our discussion on the [failure of LLN](https://intro.quantecon.org/heavy_tails.html#failure-of-the-lln)

**Comment by shlff** [comment]
Here are some of my thoughts on why the non-ergodicity is important:

First, compared to ergodicity, non-ergodic phenomena seem more common in economics and finance. 

For example, if ``alpha=0``, then the state ``1`` (unemployment) becomes an absorbing state in the lake model. This occurs when an individual, a sector or an economy hits an absorbing barrier, such as personal health shock, covid19 or the previous job hiring freezing of big tech companies in the US. 

Such situations are common as the prevalence of heavy-tails phenomena in econ and finance, linking to lecture [heavy_tails](https://intro.quantecon.org/heavy_tails.html). 

Also, the ergodic hypothesis corresponds to the assumption that individuals are representative of a group and vice versa. 

But once we introduce heterogeneity to individuals of a group, this hypothesis might not hold. The micro foundation, such as heterogeneity, plays an important role in modern macroeconomics.

These phenomena require modelling, but many existing models assume ergodicity. Therefore it is important to discuss when the ergodic theory fails. 

For those models with heterogeneous agents (households or firms), considering the failure of ergodic theory is even more important.

These ideas are quite raw, so they might need to be corrected or clarified. 

Looking forward to your comments.

**Comment by oyamad** [comment]
* We first have to clarify what "ergodicity" means. There is no definition of "ergodicity" in the lectures.
  (There is a definition of "uniform ergodicity". It is equivalent to irreducibility + aperiodicity.)
* If by "ergodicity" you mean the convergence of average visiting times (the convergence of the left hand side in [this](https://intro.quantecon.org/markov_chains_II.html#equation-llnfmc0)), then it occurs for all finite Markov chains. So if you are referring to failure of that property, it is inappropriate for finite Markov chains.
* "Heavy tails" makes sense with unbounded state spaces. So it is again orthogonal to finite Markov chains.

So I guess "Lake Model" is not an appropriate place to talk about "failure of ergodic theory"?

**Comment by jstac** [comment]
> We first have to clarify what "ergodicity" means. There is no definition of "ergodicity" in the lectures.

https://intro.quantecon.org/markov_chains_II.html#ergodicity

**Comment by oyamad** [comment]
@jstac Are you referring to "The result in (26.1) is sometimes called ergodicity"? Is the existence of a unique stationary distribution, or the irreducibility of P, part of the definition?

**Comment by jstac** [comment]
In economics, ergodicity is usually associated with the phrase "time series averages converge to cross-sectional averages".

So I suggest we use existence of a unique stationary distribution such that (26.1) holds for all initial conditions.

This should be equivalent to irreducibility in the finite state setting.

**Comment by oyamad** [comment]
It is equivalent to uniqueness of recurrent class, weaker than irreducibility (in the finite state setting).
