### ISSUE TITLE
[lecture_comparison] [re_with_feedback] Strange-looking prints of latex equations generated by code

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#38]
Hi @mmcky , I noticed another issue in lecture [re_with_feedback](https://quantecon.github.io/lecture-python.myst/re_with_feedback.html#fun-with-sympy-code):
- the latex math expressions generated by code look very strange or wrong.

For example, please see here (left: ``MYST``, right: ``RST``),

![Screen Shot 2021-01-12 at 2 06 20 pm](https://user-images.githubusercontent.com/53931041/104264657-27ad2c00-54e0-11eb-9f6c-f89953fd98d9.png)

and

![Screen Shot 2021-01-12 at 2 07 05 pm](https://user-images.githubusercontent.com/53931041/104264675-2ed43a00-54e0-11eb-9fd2-f1bd07d1f3a2.png)

and

![Screen Shot 2021-01-12 at 2 07 33 pm](https://user-images.githubusercontent.com/53931041/104264686-3398ee00-54e0-11eb-94ea-386563751b26.png)

**Comment by mmcky** [comment]
thanks @shlff -- nice pickup. I wonder if it is displaying the `html` image in preference to the `latex` via mathjax

**Comment by mmcky** [comment]
@AakashGfude perhaps this is just an issue with the priorities of which object to use at the `myst-nb` level. Would you mind investigating if `jupyter-book` is pulling an image of the math instead of the latex/mathml for mathjax rendering.

**Comment by AakashGfude** [comment]
@mmcky  you are right, it is because of the priorities set in `myst_nb`
```
"application/javascript",
"text/html",
"image/svg+xml",
"image/png",
"image/jpeg",
"text/markdown",
"text/latex",
"text/plain",
``` 

In the examples given by shu, the code blocks have `text/latex`, `text/plain`, `image/png` all of them. since `image/png` is at a higher priority, it gets used. We Will need to check why the `png` image is formed in some blocks but not others.

**Comment by mmcky** [comment]
thanks @AakashGfude should we promote `text/latex` do you think?

**Comment by mmcky** [comment]
@shlff what do you think about this: https://602a010c1e69bd5db7839bc0--nostalgic-wright-5fa355.netlify.app/re_with_feedback.html#fun-with-sympy-code

**Comment by shlff** [comment]
Thanks @mmcky. I checked all math expressions in this lecture and they look much better now except that the following one still look a bit different (left: ``myst``; right: ``rst``)

![Screen Shot 2021-02-15 at 4 36 17 pm](https://user-images.githubusercontent.com/53931041/107909401-39389680-6fac-11eb-9270-2254d710b060.png)
