### ISSUE TITLE
[lecture_comparison][FiniteMarkovChains]equation reference numbering issue

### ISSUE THREAD

**Issue by sayaikegawa** [QuantEcon/lecture-python.myst#39]
Hi @mmcky , 

I found that the number of equation reference in ```MYST``` does not coincide with that in ```RST``` in lecture 12: [Finite Markov Chains](https://python.quantecon.org/finite_markov.html#Finite-Markov-Chains).

As the screen shot shows, the equation which should be referenced as (12.4) is referenced as (12.5)  in ```MYST```. And there is not an equation which is referenced as (12.4) in ```MYST```. ( This means the equation which has a label before (12.5) is (12.3)) (left: ```RST```, right:```MYST```)

![Screen Shot 2021-01-12 at 6 57 22 pm](https://user-images.githubusercontent.com/44494439/104286814-acf90680-5509-11eb-9bfa-a66a7be16f0e.png)

I compared both files in VS code, but nothing seems to be wrong in ```MYST```. 

So far, I found this issue only in this lecture 12. So I have no idea why this happens. I'll comment when I find this issue in other lecture.

**Comment by mmcky** [comment]
thanks @sayaikegawa -- so the text reference is still ok but the numbering is a little different. Is that right? 

Does that lecture have a `12.4`?

**Comment by sayaikegawa** [comment]
Hi @mmcky , yes, that's right.

The lecture does not have ```12.4```.  I have no idea why ```12.4``` is skipped. And VS code seems ok...

**Comment by mmcky** [comment]
that is strange -- nice pickup @sayaikegawa

**Comment by mmcky** [comment]
@AakashGfude could you take the lead on this issue re: numbering. Might be part of `sphinx-multitoc-numbering`?

**Comment by AakashGfude** [comment]
@mmcky @sayaikegawa this block of maths is causing the issue:
```

(mc_fdd)=
$$
\psi_{t+1}(y) = \sum_{x \in S} P(x,y) \psi_t(x)
$$

```

because it has a label, it assumes itself as 12.4, but since it is not a ` ```{math}` myst directive. it does not display it in HTML?

**Comment by AakashGfude** [comment]
I think a reasonable solution would be to use ` ```{math}` instead here for that block?

**Comment by sayaikegawa** [comment]
Hi @AakashGfude , 

In MyST document, it says dollar delimited math can have label as follows:
![Screen Shot 2021-01-18 at 3 44 53 pm](https://user-images.githubusercontent.com/44494439/104873221-1e223900-59a4-11eb-8a07-19297280a234.png)

So, I wonder whether the equation has a label or not. Do you mean ```(mc_fdd)=``` is a label?

I'm not sure well but how about getting rid of ```(mc_fdd)=``` & ```(mc_fddv)=```? 

```
(mc_fdd)=
$$
\psi_{t+1}(y) = \sum_{x \in S} P(x,y) \psi_t(x)
$$

There are $n$ such equations, one for each $y \in S$.

If we think of $\psi_{t+1}$ and $\psi_t$ as *row vectors* (as is traditional in this literature), these $n$ equations are summarized by the matrix expression

(mc_fddv)=
```{math}
:label: fin_mc_fr

\psi_{t+1} = \psi_t P
```
```

**Comment by AakashGfude** [comment]
@sayaikegawa just tested it out and the MyST document format works nicely for numbering the equations with `$$`.
which would turn this equation to: 
```
$$
\psi_{t+1}(y) = \sum_{x \in S} P(x,y) \psi_t(x)
$$(eqn:mc_fdd)
```

if we don't want eqn nos. then we can get rid of `(mc_fdd)=` & `(mc_fddv)=`, if that's what we prefer.

**Comment by sayaikegawa** [comment]
@AakashGfude , I see. Thank you.
I think if we follow the numbering in the current website ```RST```,  
the equation 
```
(mc_fddv)=
```{math}
:label: fin_mc_fr

\psi_{t+1} = \psi_t P```
```
should be (12.4) instead of 
```$$
\psi_{t+1}(y) = \sum_{x \in S} P(x,y) \psi_t(x)
$$
```

**Comment by mmcky** [comment]
thanks @sayaikegawa and @AakashGfude it would be good to match the current live site for numbering (assuming that is correct).

**Comment by mmcky** [comment]
@sayaikegawa @AakashGfude I suspect this is due to the mix of `targets` that are being specified. I have opened https://github.com/QuantEcon/lecture-python/pull/367 which will hopefully fix this issue by removing some `link targets` that are unused.

**Comment by mmcky** [comment]
thanks @sayaikegawa this is now fixed by: https://github.com/QuantEcon/lecture-python/pull/367
