### ISSUE TITLE
"Contents" does not work

### ISSUE THREAD

**Issue by sayaikegawa** [QuantEcon/lecture-python.myst#4]
Hi @mmcky , 
The code below in md does not work in all lectures.
```
```{contents} Contents
:depth: 2
```

( In rst, 
```
.. contents:: :depth: 2
```
)

For example, in [this lecture](https://python.quantecon.org/geom_series.html),
The netlify version shows like below.
![Screen Shot 2020-10-18 at 10 43 40 pm](https://user-images.githubusercontent.com/44494439/96366426-4a56cf80-1193-11eb-9388-9115dcf9bd98.png)

Whereas, the website shows like below.
![Screen Shot 2020-10-18 at 10 44 41 pm](https://user-images.githubusercontent.com/44494439/96366459-6d817f00-1193-11eb-8472-e5a24a310315.png)

**Comment by mmcky** [comment]
thanks @sayaikegawa for reporting these issues. I will work through them this week to resolve.

**Comment by mmcky** [comment]
@sayaikegawa I think these are missing across `all` lectures. The new theme supports `contents` on the rhs.
