### ISSUE TITLE
[lecture_comparison] code-block output issue

### ISSUE THREAD

**Issue by sayaikegawa** [QuantEcon/lecture-python.myst#40]
Hi @mmcky ,

I found that code blocks have a label "Out", even though code-block is not the output of any code. This screen shot shows this issue. (left:```RST```, right:```MYST```)

![Screen Shot 2021-01-12 at 7 33 22 pm](https://user-images.githubusercontent.com/44494439/104290573-9bfec400-550e-11eb-84c1-403922fd8567.png)

This issue only happens to a code-block which is written as ```{code-block} none``` in VS code of ```MYST```.

Whereas, code-block which is written as ```{code-block} python3``` in VS code of ```MYST``` has output like below. (green box is the output) I guess that all code-block should have this form of output...

![Screen Shot 2021-01-12 at 7 59 46 pm](https://user-images.githubusercontent.com/44494439/104292461-00228780-5511-11eb-8f08-ff418be65ed8.png)

This issue happens in:
[12. Finite Markov Chains](https://python.quantecon.org/finite_markov.html)
[46. Schelling’s Segregation Model](https://python.quantecon.org/schelling.html)

**Comment by mmcky** [comment]
@sayaikegawa there shouldn't be any `out` markers for the `myst` output. In the above is the left hand side Myst or RST?

**Comment by mmcky** [comment]
@sayaikegawa I see what you're saying - nice pickup! @AakashGfude under what condition does the `Out` marker get added in `quantecon-book-theme`?
