### ISSUE TITLE
BUG: [bayes_nonconj] Execution error

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python.myst#417]
@kp992 there is an execution error being reported in the `bayes_nonconj` lecture

```bash
TypeError[0m: Called multiply with a float0 array. float0s do not support any operations by design because they are not compatible with non-trivial vector spaces. No implicit dtype conversion is done. You can use np.zeros_like(arr, dtype=np.float) to cast a float0 array to a regular zeros array. 
If you didn't expect to get a float0 you might have accidentally taken a gradient with respect to an integer argument.
```

Do you have time to look into this and open a PR?

[bayes_nonconj.err.log](https://github.com/user-attachments/files/17613963/bayes_nonconj.err.log)

@kp992 also is there any way to make these log files more useful re: syntax?

**Comment by kp992** [comment]
Sure, I will take a look into it. Thanks

**Comment by kp992** [comment]
> @kp992 also is there any way to make these log files more useful re: syntax?

I tried investigating into this. The error logged by nbclient contains Ansi color to add color formatting. I didn't find any flag to turn that off. There is a flag `NO_COLOR=1` but that didn't work while running locally. 

There is one approach where we can write a custom python script to format the error logs. So, during CI, if there are some errors, we can use that script to remove the color encoding and then upload the logs. Does that sound good?
