### ISSUE TITLE
[mle] Syntax Warning

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python.myst#424]
There is a syntax warning in `mle` producing a figure but the figure is rendering OK. 

<img width="837" alt="Screenshot 2024-12-05 at 8 13 25 am" src="https://github.com/user-attachments/assets/fd3fe700-16b4-4f2e-a003-c5a9f34feae1">

**Comment by mmcky** [comment]
@HumphreyYang do you know if these strings just need to be made `raw` strings or `format` strings. Not sure why this error is showing up in this context.

**Comment by HumphreyYang** [comment]
I think we just need to add an `r` before the string. I will fix this.

**Comment by mmcky** [comment]
thanks @HumphreyYang I am focusing on issues this morning so I might go ahead and do as you suggest with the `r`.

**Comment by HumphreyYang** [comment]
Thanks @mmcky,

I just opened a PR. Sorry I did not see your message earlier.

**Comment by mmcky** [comment]
No worries @HumphreyYang thanks.
