### ISSUE TITLE
[download notebooks] Review of Download Notebooks

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python.myst#44]
@shlff I have posted the `_notebooks` folder from `gh-pages` here from the latest 2d56ddf 

[download-notebooks.zip](https://github.com/QuantEcon/lecture-python.myst/files/5805961/download-notebooks.zip)

It would be great if you could review this collection of notebooks to see if they differ to the current set of notebooks from:

- [ ] python.quantecon.org notebooks
- [ ] and it would be nice to have a thorough review of them for checking `sphinx-tojupyter`

**Note:** These are also available from the `gh-pages` branch if we merge in future edits.

**Comment by mmcky** [comment]
@shlff here is the archive of notebooks from the current live site `python.quantecon.org/_downloads/ipynb`

[python.quantecon.org-downloadnb.zip](https://github.com/QuantEcon/lecture-python.myst/files/5811472/python.quantecon.org-downloadnb.zip)

To compare these notebooks you may want to get familiar and use a tool called [nbdime](https://github.com/jupyter/nbdime). The documentation has examples of how you compare two `ipynb` files.

**Comment by shlff** [comment]
Great thx @mmcky . Those notebooks are really helpful!

I broadly read the doc of ``nbdime``, which is a powerful and useful tool. I will get more familiar with it by comparing our notebooks.

**Comment by shlff** [comment]
Thanks @mmcky . I almost finished comparing these notebooks. 

Should I report these possible difference issues I found
- as comments in this issue or
- as issues in the issue tracker of this repository?

**Comment by mmcky** [comment]
thanks @shlff -- separate issues would be great. Can you also add `[downloadnb-comparison]` to the title to help me with the context. Thanks for your help.

**Comment by mmcky** [comment]
I think we now have separate issues documenting the issues found so I will close this.
