### ISSUE TITLE
[lecture_comparison]redundant_space_in_code

### ISSUE THREAD

**Issue by sayaikegawa** [QuantEcon/lecture-python.myst#47]
This is a minor issue that there is redundant space in some code blocks like below:

![Screen Shot 2021-01-19 at 11 33 08 am](https://user-images.githubusercontent.com/44494439/104974001-a5c28300-5a4a-11eb-8963-74ed097884d5.png)

This issues seem to occur for the codes which is imported from ```/_static/lecture_specific/```.

For example, in the above case, VS code display like below:
In ```RST```

![Screen Shot 2021-01-19 at 11 40 15 am](https://user-images.githubusercontent.com/44494439/104974210-49139800-5a4b-11eb-9d6b-a26e91bac65e.png)

In ```MyST```

![Screen Shot 2021-01-19 at 11 40 27 am](https://user-images.githubusercontent.com/44494439/104974259-706a6500-5a4b-11eb-8076-c8d9a4b91fa7.png)

This issue occurs in:
[30](https://python.quantecon.org/optgrowth.html)
[31](https://python.quantecon.org/optgrowth_fast.html)
[32](https://python.quantecon.org/coleman_policy_iter.html)

cc: @mmcky

**Comment by mmcky** [comment]
thanks @sayaikegawa -- the issue is excess newlines in the actual source file `cd_analytical`. Can you submit a PR on the `rst` repository to address this?

**Comment by sayaikegawa** [comment]
Thanks @mmcky , I'll create PRs.
