### ISSUE TITLE
[lecture_comparison]math_size_in_headings

### ISSUE THREAD

**Issue by sayaikegawa** [QuantEcon/lecture-python.myst#49]
This is a minor issue that math expressions in headings is too small in ```MyST```. I wonder whether there is any solution for this. 

The example is: (Left: ```RST```, Right: ```MyST```.)

![Screen Shot 2021-01-19 at 6 55 45 pm](https://user-images.githubusercontent.com/44494439/105004771-85b1b480-5a88-11eb-95ff-ad512e86809f.png)

cc: @mmcky

**Comment by sayaikegawa** [comment]
This issue occurs in [lecture-python-advanced](https://github.com/QuantEcon/lecture-python-advanced.myst) too.

**Comment by mmcky** [comment]
thanks @sayaikegawa -- another nice pickup. 

@AakashGfude @DrDrij is this a theme controlled element (math size in titles)?

**Comment by DrDrij** [comment]
Changed the font of the `.math` css class to use font size unit relative to it's parent.
This should mean inline Math equations should now be relative to the text surrounding them.
https://github.com/QuantEcon/quantecon-book-theme/commit/b8aa4c843a21300229e41acb53bff7c1a2c067f2
@mmcky Tested Ok (https://60263686dc45de7dbd694187--hungry-lovelace-7d0512.netlify.app/numba.html#exercise-2). Close after publish.

**Comment by mmcky** [comment]
thanks @DrDrij
