### ISSUE TITLE
Indentation does not work 

### ISSUE THREAD

**Issue by sayaikegawa** [QuantEcon/lecture-python.myst#5]
Hi @mmcky ,
I'm not quite sure this issue comes from website or netlify, because website shows an indentation for one sentence but the code  indicates an indentation for the next sentence as well.

In this [lecture](https://python.quantecon.org/multi_hyper.html#Usage),
an indentation for normal sentence does not work.

The website shows like below,
![Screen Shot 2020-10-18 at 10 54 13 pm](https://user-images.githubusercontent.com/44494439/96366667-c271c500-1194-11eb-96cb-d2fd157064b2.png)
But the netlify version shows:
![Screen Shot 2020-10-18 at 10 55 01 pm](https://user-images.githubusercontent.com/44494439/96366686-dfa69380-1194-11eb-8cdf-12e124f00b7f.png)

In the code:
rst:
```
The off-diagonal graphs plot the empirical joint distribution of
:math:`k_i` and :math:`k_j` for each pair :math:`(i, j)`.

 The darker the blue, the more data points are contained in the corresponding cell.  (Note that :math:`k_i` is on the x-axis and :math:`k_j` is on the y-axis).

 The contour maps plot the bivariate Gaussian density function of :math:`\left(k_i, k_j\right)` with the population mean and covariance given by slices of :math:`\mu` and :math:`\Sigma` that we computed above.
```
In netlify,
```
The off-diagonal graphs plot the empirical joint distribution of
$k_i$ and $k_j$ for each pair $(i, j)$.

> The darker the blue, the more data points are contained in the corresponding cell.  (Note that $> k_i$>  is on the x-axis and $> k_j$>  is on the y-axis).

> The contour maps plot the bivariate Gaussian density function of $> \left(k_i, k_j\right)$>  with the population mean and covariance given by slices of $> \mu$>  and $> \Sigma$>  that we computed above.
```

**Comment by mmcky** [comment]
this has now been fixed in `lecture-python` at the source
