### ISSUE TITLE
[downloadnb-comparison] QE brand missing in all MYST downloadnbs

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#51]
Hi @mmcky , the first issue I noticed by comparing downloadable notebooks from ``RST`` and ``MYST`` is that
- the QuantEcon brand is missing in all notebooks from ``MYST``

For example, please find a screenshot for lecture ``02_multi_hyper`` (left: ``RST``, right: ``MYST``):

![Screen Shot 2021-01-27 at 12 58 13 pm](https://user-images.githubusercontent.com/53931041/105931461-5fe76980-609f-11eb-9380-ccb612749128.png)

It occurs in ``MYST`` because notebooks from ``MYST`` do not have the following code at the place of the brand:
```
<div id="qe-notebook-header" align="right" style="text-align:right;">
        <a href="https://quantecon.org/" title="quantecon.org">
                <img style="width:250px;display:inline;" width="250px" src="https://assets.quantecon.org/img/qe-menubar-logo.svg" alt="QuantEcon">
        </a>
</div>
```

**Comment by mmcky** [comment]
thanks @shlff -- nice pickup. 

I suspect this is due to not passing through raw `html` nodes.

**Comment by shlff** [comment]
@mmcky , this issue has not been solved yet.

**Comment by shlff** [comment]
Thanks @mmcky and @DrDrij . (cc'd @jstac)

There is no QE brand in our downloadable notebooks. Shall we keep this style?
