### ISSUE TITLE
[downloadnb-comparison] Math Processing Error in many lectures

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#52]
Hi @mmcky , the second issue I find is
- there are many math processing errors in both versions (``RST`` and ``MYST``) of lots of lectures.

For example, please find a screenshot for lecture ``04_linear_algebra`` (left: ``RST``, right: ``MYST``):

![Screen Shot 2021-01-27 at 1 05 40 pm](https://user-images.githubusercontent.com/53931041/105933103-fae14300-60a1-11eb-8cc3-918fee997e08.png)

This issue occurs in the following 30 lectures:

1. ``04_linear_algebra``
2. ``06_lln_clt``
3. ``08_multivariate_normal``
4. ``14_linear_models``
5. ``20_cass_koopmans_1``
6. ``21_cass_koopmans_2``
7. ``22_mccall_model``
8. ``23_mccall_model_with_separation``
9. ``24_mccall_fitted_vfi``
10. ``25_mccall_correlated``
11. ``26_career``
12. ``28_cake_eating_problem``
13. ``29_cake_eating_numerical``
14. ``32_coleman_policy_iter``
15. ``33_egm_policy_iter``
16. ``34_ifp``
17. ``35_ifp_advanced``
18. ``36_odu``
19. ``42_lqcontrol``
20. ``43_perm_income``
21. ``44_perm_income_cons``
22. ``45_lq_inventories``
23. ``47_lake_model``
24. ``48_rational_expectations``
25. ``50_markov_perf``
26. ``51_uncertainty_traps``
27. ``53_markov_asset``
28. ``54_harrison_kreps``
29. ``56_ols``
30. ``57_mle``

**Comment by mmcky** [comment]
thanks @shlff. Is the math actually contained if you double click on the cell?

**Comment by shlff** [comment]
Thanks, @mmcky . The math is actually contained.

I double-checked them again and I find the Math Processing Errors have been fixed.

**Comment by mmcky** [comment]
Huh -- you mean this issue is resolved?  I wonder what changed :-).

**Comment by shlff** [comment]
I didn't change anything @mmcky . Yep, I guess so. 

Thanks for your time and I will close it.
