### ISSUE TITLE
[downloadnb-comparison] problematic latex math symbols in both-version notebooks

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#55]
Hi @mmcky , the 5th issue I find is 
- some latex math symbols, including $\sqrt$, $\bar$, or other superscripts or the letter below those symbols, or some subscripts, etc., are extremely higher or extremely lower than the main latex math expressions.

For example of extremely high $\bar$ or superscripts, please find a screenshot for lecture ``05_complex_and_trig`` (left: ``RST``, right: ``MYST``):
![Screen Shot 2021-01-27 at 2 17 28 pm](https://user-images.githubusercontent.com/53931041/105937881-8959c280-60aa-11eb-897f-eade25e63a9c.png)

The issue occurs in the following lectures (TBD):
-

**Comment by mmcky** [comment]
thanks @shlff looks like an issue in both. Can you edit the notebook to see if you can fix this and then document what the `markdown cell` should contain.

**Comment by shlff** [comment]
Thanks, @mmcky . I checked the notebooks again and surprised to find the appearance of these math symbols are normal now.

**Comment by mmcky** [comment]
Thanks @shlff -- if this is resolved can you close the issue. Thanks.

**Comment by shlff** [comment]
Thanks @mmcky . This issue has been solved and I will close this issue.
