### ISSUE TITLE
[downloadnb-comparison] abnormal small latex brackets in both-version lectures

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#56]
Hi @mmcky , the 6th issue I noticed is
- the latex brackets for vectors or matrices are extremely small in notebooks from both-version lectures.

For example, please find a screenshot for lecture ``04_linear_algebra`` (left: ``RST``, right: ``MYST``):

![Screen Shot 2021-01-27 at 2 44 05 pm](https://user-images.githubusercontent.com/53931041/105939881-341fb000-60ae-11eb-93c5-d4be21bf05af.png)

**Comment by mmcky** [comment]
@shlff can you try and fix this in the notebook and post what the output should be to get this rendering in the notebook properly?

**Comment by shlff** [comment]
Thanks @mmcky . I checked the notebooks again and surprised to find the appearance of these brackets are normal now.

**Comment by mmcky** [comment]
@shlff sounds like `mathjax` wasn't loading for you on the day you reviewed. Can you review these and close the necessary issues. Thanks.

**Comment by shlff** [comment]
Thanks @mmcky . You are right and now I can confirm that this issue has gone.

I will close this issue.
