### ISSUE TITLE
[downloadnb-comparison] [04_linear_algebra] a sentence is missing in MYST

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#57]
Hi @mmcky , I noticed the following sentence is missing in lecture ``04_linear_algebra``:
- ``The solution is known to be $ \hat x = (A'A)^{-1}A'y $ — see for example chapter 3 of <a href=_static/lecture_specific/linear_algebra/course_notes.pdf download>these notes</a>.``

Please find a screenshot for the corresponding place of lecture ``04_linear_algebra`` (left: ``RST``, right: ``MYST``):

![Screen Shot 2021-01-27 at 3 38 41 pm](https://user-images.githubusercontent.com/53931041/105944342-38040000-60b7-11eb-933d-9a430f44387d.png)

**Comment by mmcky** [comment]
thanks @shlff -- nice pickup. Any ideas looking at the source what might be causing this? Is it in the `rst` and `md` file?

**Comment by shlff** [comment]
Thanks @mmcky . This is in the notebook generated from the ``md`` file.

**Comment by mmcky** [comment]
thanks @shlff -- looks like the `only` directive isn't getting included by `jupyter-book`

**Comment by mmcky** [comment]
@shlff here is the list of all `only` directives used in the lectures. 

lectures/aiyagari.md:```{only} html
lectures/aiyagari.md:```{only} latex
lectures/linear_algebra.md:```{only} html
lectures/linear_algebra.md:```{only} latex
lectures/linear_models.md:```{only} html
lectures/linear_models.md:```{only} latex
lectures/mle.md:```{only} html
lectures/mle.md:```{only} latex

would you mind checking if this is broken in the other lectures as well.

**Comment by shlff** [comment]
Thanks @mmcky . I checked all the corresponding places just now and I can confirm that the ``only`` directives are broken in the ``myst``-version of following lectures:
- [aiyagari](https://github.com/QuantEcon/lecture-python.myst/blob/main/lectures/aiyagari.md),
- [linear_algebra](https://github.com/QuantEcon/lecture-python.myst/blob/main/lectures/linear_algebra.md),
- [linear_models](https://github.com/QuantEcon/lecture-python.myst/blob/main/lectures/linear_models.md),
- [mle](https://github.com/QuantEcon/lecture-python.myst/blob/main/lectures/mle.md)

**Comment by mmcky** [comment]
thanks @shlff -- it would be great if you could setup PR's on `lecture-python.myst` that removes the `only` directives with unified syntax (i.e. markdown) and then add the tag `manual-change`.

**Comment by mmcky** [comment]
thanks @shlff closing this as the PR is capturing this change.
