### ISSUE TITLE
[downloadnb-comparison] [05_complex_and_trig] SymPyDeprecationWarning in both RST and MYST

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#58]
Good afternoon, @mmcky , I find a ``SymPyDeprecationWarning`` in both notebooks of ``MYST`` and ``RST`` and ``MYST``-website lecture [05_complex_and_trig](https://quantecon.github.io/lecture-python.myst/complex_and_trig.html).

Please find a screenshot for the corresponding place of lecture ``05_complex_and_trig`` (left: ``RST``, right: ``MYST``):
![Screen Shot 2021-01-27 at 3 55 27 pm](https://user-images.githubusercontent.com/53931041/105944970-71893b00-60b8-11eb-8453-91cdc312b344.png)

Do you think I should create a PR to manually fix this issue?

**Comment by mmcky** [comment]
@shlff does this show up in the `html` as well? Please submit a PR to fix if you can.

**Comment by shlff** [comment]
Yes, @mmcky . It also shows up in the ``html`` generated by ``md``, and please see here: https://quantecon.github.io/lecture-python.myst/complex_and_trig.html

I will create a PR in this repo to fix it.
