### ISSUE TITLE
[downloadnb-comparison] [08_multivariate_normal] problematic inserted latex math

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#59]
Hi @mmcky , I noticed the following issue in both the notebook and the website of ``MYST`` lecture [08_multivariate_normal](https://quantecon.github.io/lecture-python.myst/multivariate_normal.html):
- ``‘math:x`` should be $x$.

Please find a screenshot for the corresponding place of lecture ``08_multivariate_normal`` (left: ``RST``, right: ``MYST``):

![Screen Shot 2021-01-27 at 4 00 21 pm](https://user-images.githubusercontent.com/53931041/105945806-15bfb180-60ba-11eb-826c-fe90078bfbe6.png)

**Comment by mmcky** [comment]
@shlff would you mind posting what the `md` syntax is here. This might an issue we should fix in `sphinx-tomyst` if inline math isn't working in nested list contexts properly
