### ISSUE TITLE
The list number does not work

### ISSUE THREAD

**Issue by sayaikegawa** [QuantEcon/lecture-python.myst#6]
Hi @mmcky 
In this [lecture](https://python.quantecon.org/linear_algebra.html#Solutions), the list number doest not work.

**The website shows like below**
![Screen Shot 2020-10-18 at 11 15 11 pm](https://user-images.githubusercontent.com/44494439/96367148-b0455600-1197-11eb-919e-3b85492a8d43.png)

**But the netlify version shows**

![Screen Shot 2020-10-18 at 11 16 06 pm](https://user-images.githubusercontent.com/44494439/96367172-d23ed880-1197-11eb-9fe3-60ba86fbe1c3.png)

**I think ```^^.``` should removed in website, but it is strange that the list number in netlify version does not work.**

**Comment by mmcky** [comment]
thanks @sayaikegawa - have updated this at the source `rst` as this is incorrect syntax. 

https://github.com/QuantEcon/lecture-python/pull/271
