### ISSUE TITLE
[downloadnb-comparison] [14_linear_models] a sentence disappears in MYST

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#60]
Hi @mmcky , I find the following sentence is missing in ``MYST`` notebook of lecture [14_linear_models](https://quantecon.github.io/lecture-python.myst/linear_models.html#conditions-for-stationarity):
- ``This is the *globally stable case* — see <ahref=_static/lecture_specific/linear_models/iteration_notes.pdfdownload>these notes</a> for more a theoretical treatment.``

Please find a screenshot for the corresponding place of lecture ``14_linear_models`` (left: ``RST``, right: ``MYST``):

![Screen Shot 2021-01-27 at 4 12 43 pm](https://user-images.githubusercontent.com/53931041/105947383-1e65b700-60bd-11eb-9d7c-25c409f6dfad.png)

**Comment by mmcky** [comment]
@shlff I suspect this is also due to `only` directive usage.

**Comment by mmcky** [comment]
@shlff would you mind to take a look to see if we really `need` these `only` directives between `html` and `latex`. Maybe with the `jupyter-book` system we can get rid of this distinction and just link the same document using markdown. What do you think?

**Comment by shlff** [comment]
Thanks @mmcky . I agree with you. If we use markdown and jupyterbook, then we don't need ``only`` directive to distinguish HTML and latex.

**Comment by mmcky** [comment]
When you're ready could you make a PR on `lecture-python.myst` to remove the `only` directives and then mark that PR with `manual-change` so we don't merge it.

**Comment by mmcky** [comment]
thanks @shlff closing this as PR #100 captures this change
