### ISSUE TITLE
[downloadnb-comparison] [19_short_path] a link issue

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#61]
Hi @mmcky , I noticed that following issue in lecture [19_short_path](https://quantecon.github.io/lecture-python.myst/short_path.html)  (left: ``RST``, right: ``MYST``):

![Screen Shot 2021-01-27 at 4 36 08 pm](https://user-images.githubusercontent.com/53931041/105947763-d2674200-60bd-11eb-872a-d43cfbc5c369.png)

Do you think it is a good idea for me to create a PR to fix this issue manually in this repo or in ``RST`` repo?

**Comment by mmcky** [comment]
@shlff this looks like the `md` link is split across lines? If there is incorrect `RST` at the source please go ahead and make a PR. Thanks.

**Comment by shlff** [comment]
Thanks @mmcky . I checked that this issue has been solved.

![Screen Shot 2021-03-11 at 11 07 42 am](https://user-images.githubusercontent.com/53931041/110715798-0788b780-825a-11eb-8929-a5136a80429b.png)
