### ISSUE TITLE
[downloadnb-comparison] [21_cass_koopmans_2] SyntaxWarning

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#62]
Hi @mmcky , I find the following ``SyntaxWarning`` in lecture [21_cass_koopmans_2](https://quantecon.github.io/lecture-python.myst/cass_koopmans_2.html) (left: ``RST``, right: ``MYST``):

![Screen Shot 2021-01-27 at 4 48 35 pm](https://user-images.githubusercontent.com/53931041/105948717-8cab7900-60bf-11eb-8716-fe600d6f9397.png)

![Screen Shot 2021-01-27 at 4 51 08 pm](https://user-images.githubusercontent.com/53931041/105948899-ead85c00-60bf-11eb-9100-a14add23d05a.png)

This issue can be fixed by changing ``is`` to ``==``.

Do you think it is a good idea for me to create a PR to fix it in ``RST`` repo?

**Comment by mmcky** [comment]
@shlff yes please -- that would be great to get rid of these warnings.
