### ISSUE TITLE
[downloadnb-comparison] [27_jv] A quoted code cell becomes a compiling code cell in MYST downloadnb

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#63]
Hi @mmcky , I find an issue in lecture [27_jv](https://quantecon.github.io/lecture-python.myst/jv.html#exercises):
- A quoted code cell becomes a compiling code cell in ``MYST`` notebook.

Please find a screenshot for the corresponding place of lecture ``27_jv`` (left: ``RST``, right: ``MYST``):

![Screen Shot 2021-01-27 at 5 07 56 pm](https://user-images.githubusercontent.com/53931041/105950304-40156d00-60c2-11eb-9d99-8541e0f50389.png)

**Comment by mmcky** [comment]
thanks @shlff -- do you mind posting what the `rst` and `md` sources are to see why this is getting converted to a cell-block. thanks.

**Comment by shlff** [comment]
Thanks @mmcky . Please look at a screenshot of the corresponding parts of the ``rst`` and ``md`` sources (left: ``RST``, right: ``MYST``):

![Screen Shot 2021-02-03 at 6 52 39 pm](https://user-images.githubusercontent.com/53931041/106715555-5175f080-6651-11eb-8257-f474b948fef0.png)

**Comment by mmcky** [comment]
thanks @shlff  -- I am surprised the `code-block` get's converted to a code cell as I thought `myst-nb` and `jupytext` only converted `code-cell` directives. Will need to look into this. 

- [ ] setup a myst `md` file with a `code-block` and `code-cell` with `jupytext` headers to see how it converts to notebooks.

**Comment by shlff** [comment]
Thanks @mmcky . This issue has not have been solved yet and please see the following screenshot of the notebook downloaded from the site.

![Uploading Screen Shot 2021-03-11 at 11.05.28 am.png…]()

**Comment by shlff** [comment]
Thanks @mmcky . This is no longer an issue. I will close it.
