### ISSUE TITLE
[downloadnb-comparison] [37_likelihood_ratio_process] a link is problematic

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#64]
Hi @mmcky , the following link to ``Neyman-Pearson Lemma`` in [37_likelihood_ratio_process](https://quantecon.github.io/lecture-python.myst/likelihood_ratio_process.html#likelihood-ratio-test) can be problematic:
- https://en.wikipedia.org/wiki/Neyman%E2%80%93Pearson_lemma

which is https://en.wikipedia.org/wiki/Neyman–Pearson_lemma in ``RST`` version.

Please find a screenshot for the corresponding place of lecture ``37_likelihood_ratio_process`` (left: ``RST``, right: ``MYST``) (they look the same but the links are different):

![Screen Shot 2021-01-27 at 5 31 09 pm](https://user-images.githubusercontent.com/53931041/105952298-7e605b80-60c5-11eb-96b0-6946b0838339.png)

**Comment by mmcky** [comment]
@shlff can you change that in the source `rst` file? Or is the `%` getting added by the translation process?

**Comment by shlff** [comment]
Thanks @mmcky , the link in the source ``rst`` file is https://en.wikipedia.org/wiki/Neyman%E2%80%93Pearson_lemma.

It seems that the ``%`` is added by the translation process.

**Comment by mmcky** [comment]
thanks @shlff

**Comment by mmcky** [comment]
@shlff when I look at `rst` and `md` the link is without the `%` so I agree this must be coming from `sphinx-tojupyter`.

**Comment by mmcky** [comment]
@shlff I can't seem to replicate this issue

https://602b1025e4ec29b32759bff3--nostalgic-wright-5fa355.netlify.app/likelihood_ratio_process.html

and downloaded the `notebook` from there which should be generated by `sphinx_tojupyter`.

**Comment by shlff** [comment]
Thanks @mmcky . Do you want me to manually fix the link issue in repo ``lecture-python.myst``?

**Comment by mmcky** [comment]
@shlff in the latest build this link doesn't appear broken to me. Not sure it needs fixing. Can you check?

**Comment by shlff** [comment]
Thanks @mmcky , the link in the latest build or in the ``myst`` file mentioned above is:
- https://en.wikipedia.org/wiki/Neyman%E2%80%93Pearson_lemma

which **works** but just differs from the link in the original ``rst`` file:
- https://en.wikipedia.org/wiki/Neyman–Pearson_lemma

**Comment by mmcky** [comment]
oh that is ok -- it it `works` that is fine. `sphinx` is probably doing some changes to remove `-` into general `url` character syntax.
