### ISSUE TITLE
[downloadnb-comparison] [57_mle] an internal link/ref of contents is not working

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#65]
Hi @mmcky , the following internal link/ref of contents in lecture ``57_mle`` is not working in both versions (left: ``RST``, right: ``MYST``):

![Screen Shot 2021-01-27 at 9 50 16 pm](https://user-images.githubusercontent.com/53931041/105981360-17a16900-60ea-11eb-9732-0adc197dc1d2.png)

**Comment by mmcky** [comment]
@shlff where is the link trying to resolve to when you double click the `markdown` cell in the notebook?

**Comment by shlff** [comment]
@mmcky , the link is trying to resolve to section [Maximum Likelihood Estimation with `statsmodels`](https://quantecon.github.io/lecture-python.myst/mle.html#maximum-likelihood-estimation-with-statsmodels) of lecture ``57_mle``.

Please see the following code:
- ``[Maximum Likelihood Estimation with `statsmodels`](#Maximum-Likelihood-Estimation-with-`statsmodels`)``

**Comment by mmcky** [comment]
- [ ] must be an issue in `sphinx-tojupyter`

**Comment by mmcky** [comment]
@shlff this build in PR #43 should be using the latest sphinx-tojupyter.

https://6038cc9d13761dc1d83bf515--nostalgic-wright-5fa355.netlify.app/intro.html

Can you check this issue and close it if resolved?

**Comment by shlff** [comment]
Thanks @mmcky . This internal link is still not working.

**Comment by shlff** [comment]
Thanks @mmcky . I can confirm that this issue has been solved now.
