### ISSUE TITLE
[downloadnb-comparison] different numbering system for math tags and their citations in contexts

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#66]
Hi @mmcky , I noticed that in all ``MYST`` notebooks/website lectures:
- math tags and their citations in context use two different kinds of numbering systems.

For example, please find a screenshot for lecture ``03_sir_model`` (left: ``RST``, right: ``MYST``):

![Screen Shot 2021-01-27 at 10 11 10 pm](https://user-images.githubusercontent.com/53931041/105983581-158cd980-60ed-11eb-90b2-3cbbbd7edbf6.png)

**Comment by mmcky** [comment]
Does the new numbering system match the `html` version?

**Comment by shlff** [comment]
Thanks @mmcky . In the ``MYST``-version notebooks (please see the right side of the screenshot above), 
- the numbering system for **citations** in the contexts **matches** the ``MYST``-version ``html`` files (e.g., the ``(1.2)`` as I circled),
- the numbering system for **math expressions** does **not match** the ``MYST``-version ``html`` files (e.g., the ``(2)`` as I circled).

**Comment by mmcky** [comment]
ohh - thanks @shlff I see the real issue here now. 

I suspect that `sphinx-tojupyter` is using its own `numbering` when writing `\tag{}` as we did in `jupinx` rather than using the internal `sphinx` values.

**Comment by mmcky** [comment]
@AakashGfude just trying to replicate the `tag` numbering that must be done by `sphinx-multitoc-numbering`. 

Can you point me to where these values for `refid` are constructed. Are they part of a transform and you generate these nested numbers?

```xml
> /Users/matthewmckay/repos-collab/sphinx-tojupyter/sphinx_tojupyter/writers/translate_all.py(321)visit_math_block()                                   
-> referenceBuilder = " \\tag{" + str(node["number"]) + "}\n"
(Pdb) node.pformat()
'<math_block docname="numpy" ids="equation-np-polynom" label="np_polynom" nowrap="False" number="1" xml:space="preserve">\n    p(x) = a_0 + a_1 x + a_2 x^2 + \\cdots a_N x^N = \\sum_{n=0}^N a_n x^n\n'
(Pdb) c
> /Users/matthewmckay/repos-collab/sphinx-tojupyter/sphinx_tojupyter/writers/translate_all.py(612)depart_reference()
-> refid = node["refid"]
(Pdb) node.pformat()
'<reference internal="True" refid="equation-np-polynom">\n    (9.1)\n'
```

**Comment by mmcky** [comment]
Just wondering where I might be able to get the `chapter` or value `9` in the above example from in the `sphinx` configuration

**Comment by mmcky** [comment]
@shlff this build in PR #43 should be using the latest `sphinx-tojupyter`. 

https://6038cc9d13761dc1d83bf515--nostalgic-wright-5fa355.netlify.app/intro.html

Can you check this issue and close it if resolved?

**Comment by shlff** [comment]
Great thanks for your hard-working @mmcky and @AakashGfude . 

I can confirm that this issue has been solved and will close this issue.
