### ISSUE TITLE
Reference inside of lists does not work

### ISSUE THREAD

**Issue by sayaikegawa** [QuantEcon/lecture-python.myst#7]
Hi @mmcky ,
In this [lecture](https://python.quantecon.org/heavy_tails.html#Overview),
the reference links should be inside of lists. (but now it is outside of lists in netlify version.)

**The website shows:**
![Screen Shot 2020-10-18 at 11 30 06 pm](https://user-images.githubusercontent.com/44494439/96367476-c5bb7f80-1199-11eb-96ab-8b33b69f241c.png)
The code in rst
```
* the income distributions and the wealth distribution (see, e.g., :cite:`pareto1896cours`, :cite:`benhabib2018skewed`),

* the firm size distribution (:cite:`axtell2001zipf`, :cite:`gabaix2016power`}),

* the distribution of returns on holding assets over short time horizons (:cite:`mandelbrot1963variation`, :cite:`rachev2003handbook`), and

* the distribution of city sizes (:cite:`rozenfeld2011area`, :cite:`gabaix2016power`).
```

**But the netlify verstion shows:**
![Screen Shot 2020-10-18 at 11 30 47 pm](https://user-images.githubusercontent.com/44494439/96367491-dec43080-1199-11eb-897a-74eecc811471.png)

The code in md 
```
{cite}`pareto1896cours`{cite}`benhabib2018skewed`{cite}`axtell2001zipf`{cite}`gabaix2016power`{cite}`mandelbrot1963variation`{cite}`rachev2003handbook`{cite}`rozenfeld2011area`{cite}`gabaix2016power`* the income distributions and the wealth distribution (see, e.g., , ),
* the firm size distribution (, }),
* the distribution of returns on holding assets over short time horizons (, ), and
* the distribution of city sizes (, ).
```

**Comment by mmcky** [comment]
thanks @sayaikegawa -- yup this needs to be fixed. 

The `visit_reference` methods aren't compatible with `lists` and `tables` in `sphinx-tomyst`

**Comment by mmcky** [comment]
This is fixed by https://github.com/executablebooks/sphinx-tomyst/pull/82
