### ISSUE TITLE
[jupyterbook-latex]chapter_number

### ISSUE THREAD

**Issue by sayaikegawa** [QuantEcon/lecture-python.myst#73]
Hi @AakashGfude , I'm not able to add a label for some reason so I write it in title.

This is a minor issue about a description of chapter number.

In ```jupyter-book```, chapter number is written both in digit and word. It may be better to make it consistent about description.

Left:```jupyter-book``` Right: ```website```
![Screen Shot 2021-02-03 at 6 30 33 pm](https://user-images.githubusercontent.com/44494439/106713235-44a3cd80-664e-11eb-93f0-e22768116500.png)

**Comment by AakashGfude** [comment]
Thanks @sayaikegawa  for raising this one. This is actually the default style added by sphinx, which uses a package called `fancychap` to styles chapter headers. We can either use one of the styles provided by the package or customize it to suit our needs(which will take a bit more effort) .

For the list of header styles provided by this package. Refer to chapter 3 of the pdf which I have attached below
[fncychap.pdf](https://github.com/QuantEcon/lecture-python.myst/files/5929981/fncychap.pdf)

As you can see, the present style is "Bjarne" , we can choose another one from the list instead which has chapter number in digit ?

**Comment by sayaikegawa** [comment]
Thank you @AakashGfude . There are so many options...

Hi @jstac , 
As my comment above, I found that the expressions of chapter number are different in "footer" and "chapter title" of ```jupyterbook-pdf``` (digit in "footer", word in "chapter title"). I just wonder whether it is ok or not. If it is fine, I'll close this issue. But if not, could you pick a "chapter style" to use from the link in Aakash's comment, please?

**Comment by mmcky** [comment]
thanks @sayaikegawa and @AakashGfude. 

Given the information content is the same I will tag this as `low` priority but this is a great `style` question about whether the default should match between `html` and `pdf`
