### ISSUE TITLE
[jupyterbook-latex]beta is not compiled properly

### ISSUE THREAD

**Issue by sayaikegawa** [QuantEcon/lecture-python.myst#74]
Hi @AakashGfude ,

β sometime is not compiled properly in pdf like below.
Left```jupyter-book``` Right```website```

![Screen Shot 2021-02-03 at 7 10 26 pm](https://user-images.githubusercontent.com/44494439/106725977-06160f00-665e-11eb-9b8b-604fe29c4c8c.png)

In [this lecture](https://python.quantecon.org/mccall_model.html), β is not compiled properly only when ```β```  is used in non code-block place in VS code. When ```\beta``` is used, it is compiled properly.

**Comment by AakashGfude** [comment]
Thanks @sayaikegawa , have added handling of β with this PR https://github.com/executablebooks/jupyterbook-latex/pull/32 .
Will keep an eye for other greek characters as well.

**Comment by sayaikegawa** [comment]
Thanks @AakashGfude .
