### ISSUE TITLE
[jupyterbook-latex]math signal 

### ISSUE THREAD

**Issue by sayaikegawa** [QuantEcon/lecture-python.myst#76]
Hi @AakashGfude ,
I found that some math signals in ```jupyterbook-pdf``` are a little strange. 
Here are the signals I found strange.
Left:```jupyterbook-latex``` Right:```website```
![Screen Shot 2021-02-05 at 9 34 01 pm](https://user-images.githubusercontent.com/44494439/107026492-e1a56880-67fe-11eb-9de5-43e4f3d752cf.png)
![Screen Shot 2021-02-05 at 9 53 27 pm](https://user-images.githubusercontent.com/44494439/107026505-e79b4980-67fe-11eb-8f95-cdc3c3b3bca4.png)

Is there any better way to express those signals?

**Comment by mmcky** [comment]
thanks @sayaikegawa -- is this just a rendering issue. Is the `tex`/`html`/`md` the same between these two comparisons?

@AakashGfude let me know if you need my input on this.

**Comment by AakashGfude** [comment]
Thanks @mmcky and @sayaikegawa , it was a rendring issue of pdf. due to lack of proper handling of unicode chars in math.
