### ISSUE TITLE
New lecture on income inequality

### ISSUE THREAD

**Issue by Harveyt47** [QuantEcon/lecture-python.myst#78]
New data-centric lecture on changes in income inequality.

One area of interest is how income inequality has changed over time and space. i.e. has income inequality increased in country X over the past 100 years?

This [paper]( https://www.newyorkfed.org/medialibrary/media/research/epr/2019/epr_2019_wage-inequality_abel-deitz.pdf) looks at wage inequality in different areas of the US and does analysis of it over time.

Possible data source for US data is the [Survey of Consumer Finances (SCF)]( https://www.federalreserve.gov/econres/aboutscf.htm)

We should try to make this flow on from the [wealth dynamics lecture]( https://python.quantecon.org/wealth_dynamics.html). As well as making use of its code as much as we can. 

Lecture could look something like this.

-	overview: flowing on from wealth dynamics; premise of the questions we will aim to answer (has income inequality increased over time?); brief intro to the data we will use.
-	Refresh of Gini coeff and Lorenz curves, a bit of code illustrating them.
-	Description of the data. With some documentation on how we sourced it and cleaned it.
-	Implementing Lorenz curve and Gini coefficient to the data. (graph Gini coefficients over time)
-	Discussion and interpretation of the results.

CC: @najuzilu @shlff @sayaikegawa

**Comment by ericvd-ucb** [comment]
Hey @Harveyt47 did this noteboook ever get made?  Looking for an empirical hostorical data Gini inequality notebook!

**Comment by jstac** [comment]
Hi @ericvd-ucb , thanks for prompting us on this.  I'll be glad to hear about how your project pans out.

Somewhat connected: As part of this activity we ended up adding some functionality to QuantEcon related to inequality.  See https://quanteconpy.readthedocs.io/en/latest/tools/inequality.html.

@shlff and @natashawatkins, do you have anything that might be useful to @ericvd-ucb ?
