### ISSUE TITLE
Output of code does not work in [Heavy-Tailed Distribution]

### ISSUE THREAD

**Issue by sayaikegawa** [QuantEcon/lecture-python.myst#8]
Hi @mmcky ,

In this [lecture](https://python.quantecon.org/heavy_tails.html), all the codes do not show the outputs.

For example,

The website shows
![Screen Shot 2020-10-18 at 11 41 11 pm](https://user-images.githubusercontent.com/44494439/96367725-521a7200-119b-11eb-9e9b-4bdcba1f3f27.png)

But the netlify version shows
![Screen Shot 2020-10-18 at 11 41 46 pm](https://user-images.githubusercontent.com/44494439/96367740-678f9c00-119b-11eb-984a-14bfc568bb27.png)

**Comment by mmcky** [comment]
https://5f97827cccb83046f9092346--nostalgic-wright-5fa355.netlify.app/heavy_tails.html#heavy-tails-in-asset-returns

this seems to be working now. Closing.
