### ISSUE TITLE
[jupyterbook-latex] [wald_friedman] extra > symbols in a math expression

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#89]
Hi @AakashGfude and @mmcky, the 3rd issue is that in lecture [wald_friedman](https://python.quantecon.org/wald_friedman.html)
- there are extra $>$ symbols in a math expression.

Please see the screenshot (left: PDFs generated by ``rst``, right: PDFs generated by ``myst``):

![Screen Shot 2021-02-11 at 4 42 29 am](https://user-images.githubusercontent.com/53931041/107549537-0ac16100-6c24-11eb-90ed-cc52f2381adb.png)

Please see their ``rst`` and ``myst`` files respectively (left: ``rst``, right: ``myst``):

<img width="721" alt="Screen Shot 2021-02-11 at 4 47 27 am" src="https://user-images.githubusercontent.com/53931041/107549805-5aa02800-6c24-11eb-8c65-ecbee992a0a7.png">

It seems that the ``>``symbols are added during translation, which might be read mistakenly by latex.

**Comment by mmcky** [comment]
@shlff can you test your fix for this and let me know if that works. You linked elsewhere some syntax issue with using `>` for all the `math` lines.

**Comment by mmcky** [comment]
Saya reported a fix for this issue in #105
