### ISSUE TITLE
lecture links in left [Table of Contents] bar fail to work

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#9]
Hi @mmcky , the lecture links in the left [Contents] bars of home page and all lecture pages are not working.
- For example, when you click [lecture-python](https://5f8f79757d3634008881552f--nostalgic-wright-5fa355.netlify.app/), we cannot use the lecture links of the left ``Table of Contents`` bar to go to the lecture we want, clicking those links just direct you nowhere but stay at the same webpage.
- The same issues occur in [lecture-python-advanced](https://5f8f75adae96290088736dae--wonderful-lalande-528d1c.netlify.app/intro.html).

I am not sure whether this issue would exist for ``gh-pages`` versions and will keep you posted.

**Comment by mmcky** [comment]
@shlff can you check this against: https://5f97827cccb83046f9092346--nostalgic-wright-5fa355.netlify.app/intro.html#

and let me know.

**Comment by shlff** [comment]
Thanks, @mmcky . Now the links in the left [Table of Contents] work well in the updated website.

**Comment by mmcky** [comment]
thanks @shlff
