### ISSUE TITLE
[jupyterbook-latex] no section numbers in the contents

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#90]
Hi @AakashGfude and @mmcky , I also noticed that 
- there are no section numbers in the contents.

For example, please see the following screenshot (left: PDFs generated by ``rst``, right: PDFs generated by ``myst``):
![Screen Shot 2021-02-11 at 4 50 16 am](https://user-images.githubusercontent.com/53931041/107550314-fc277980-6c24-11eb-8646-030af5565780.png)

**Comment by mmcky** [comment]
@jstac this is a style issue really. I actually prefer the local `contents` listing to be without the numbers (and just links). What do you think?

**Comment by shlff** [comment]
@mmcky , I also prefer the ``content`` listing without the numbers, or at least the numbers to be the front of each item.

**Comment by mmcky** [comment]
I think links without numbers is better so let's close this.
