### ISSUE TITLE
[jupyterbook-latex] [lake_model] a broken internal link

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#93]
Hi @AakashGfude and @mmcky , there is a broken link in lecture [lake_model](https://python.quantecon.org/lake_model.html) of PDFs generated by ``myst``.

Please see the screenshot (left: PDFs generated by ``rst``, right: PDFs generated by ``myst``):

![Screen Shot 2021-02-11 at 6 13 59 am](https://user-images.githubusercontent.com/53931041/107559553-5a0d8e80-6c30-11eb-84d3-edd0fc6fabba.png)

**Comment by mmcky** [comment]
@shlff can you post the `rst` and `markdown` to see where the issue is for this.

**Comment by shlff** [comment]
Sure, @mmcky . Please see (left: ``rst``, right: ``myst``):

![Screen Shot 2021-02-15 at 10 53 21 pm](https://user-images.githubusercontent.com/53931041/107943407-c564b100-6fe0-11eb-8b22-3a4605ecf2b1.png)

**Comment by mmcky** [comment]
ah ha -- thanks @shlff it looks like the `role` isn't parsed correctly due to being over two lines.

**Comment by mmcky** [comment]
thanks @shlff I have fixed this in the source `rst` directory.
