### ISSUE TITLE
[jupyterbook-latex] a mistakenly-compiling latex for $\mathbb 1$

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#94]
Hi @AakashGfude and @mmcky , I find that all $\mathbb 1$s are mistakenly compiled by latex.

For example, in lecture [lqcontrol](https://python.quantecon.org/lqcontrol.html), please see the screenshot (left: PDFs generated by ``rst``, right: PDFs generated by ``myst``):

![Screen Shot 2021-02-11 at 6 18 55 am](https://user-images.githubusercontent.com/53931041/107560155-1cf5cc00-6c31-11eb-8326-b9e524937b59.png)

Also for example, in lecture [markov_asset](https://python.quantecon.org/markov_asset.html), please see the screenshot (left: PDFs generated by ``rst``, right: PDFs generated by ``myst``):

![Screen Shot 2021-02-11 at 8 48 52 am](https://user-images.githubusercontent.com/53931041/107577049-102fa300-6c46-11eb-8e0b-155b6e81741f.png)

**Comment by AakashGfude** [comment]
\mathbb has been handled now, and is in the latest `jupyterbook_latex`

<img width="910" alt="Screen Shot 2021-02-16 at 11 55 17 am" src="https://user-images.githubusercontent.com/6542997/108005807-d7c90400-704d-11eb-9140-4ec832363d88.png">
