### ISSUE TITLE
[jupyterbook-latex] [re_with_feedback] problematic math outputs generated by code

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#95]
Hi @AakashGfude and @mmcky , I find that in lecture [re_with_feedback](https://python.quantecon.org/re_with_feedback.html),
- some outputs (especially numbers) generated by code look a bit weird,
- some outputs (especially math expressions) are mistakenly printed.

Please see the screenshot of strange number outputs (left: PDFs generated by ``rst``, right: PDFs generated by ``myst``):

![Screen Shot 2021-02-11 at 8 24 21 am](https://user-images.githubusercontent.com/53931041/107574236-94802700-6c42-11eb-92fd-41b989f4ad12.png)

Please see the screenshot of wrong math outputs (left: PDFs generated by ``rst``, right: PDFs generated by ``myst``):

![Screen Shot 2021-02-11 at 8 25 54 am](https://user-images.githubusercontent.com/53931041/107574802-330c8800-6c43-11eb-9995-e634fa673c5c.png)

and

![Screen Shot 2021-02-11 at 8 28 15 am](https://user-images.githubusercontent.com/53931041/107574815-3738a580-6c43-11eb-8955-e6d7c8b8ca38.png)

**Comment by mmcky** [comment]
thanks @shlff this does need improvement. 

the second case with misaligned outputs is concerning. So I have tagged this as `high-priority` for review

**Comment by mmcky** [comment]
@AakashGfude in d6fb77c I have updated the priority for pure `latex` output which may help this issue.

**Comment by mmcky** [comment]
@AakashGfude When you get a chance would you mind to regenerate the `pdf` after the last iteration on https://github.com/executablebooks/jupyter-book/pull/1167 to see if this is fixed from the `reordering`

**Comment by AakashGfude** [comment]
Thanks @mmcky , using your PR in `myst-nb` https://github.com/executablebooks/MyST-NB/pull/305, the output seems to be rendering nicely. 

<img width="565" alt="Screen Shot 2021-03-01 at 3 34 48 pm" src="https://user-images.githubusercontent.com/6542997/109452353-aae00c80-7aa3-11eb-9aa2-342641ff39c8.png">
<img width="533" alt="Screen Shot 2021-03-01 at 3 36 00 pm" src="https://user-images.githubusercontent.com/6542997/109452437-d6fb8d80-7aa3-11eb-9dd1-bf403aa01e9f.png">

**Comment by mmcky** [comment]
@AakashGfude can you review this -- is this still an issue?

**Comment by AakashGfude** [comment]
hi @mmcky looks like it is still an issue. From what I saw on the website. Probably because the PR https://github.com/executablebooks/MyST-NB/pull/305 wasn't merged?
