### ISSUE TITLE
[jupyterbook-latex] [markov_perf] [pandas_panel] many python outputs are missing

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#96]
Hi @AakashGfude and @mmcky , I find that
- in lecture [markov_perf](https://python.quantecon.org/markov_perf.html), almost all python outputs are missing. For example, please see the following screenshot (left: PDFs generated by ``rst``, right: PDFs generated by ``myst``)

![Screen Shot 2021-02-11 at 8 41 02 am](https://user-images.githubusercontent.com/53931041/107576346-1c673080-6c45-11eb-9f03-38076d3fd763.png)

- in lecture [pandas_panel](https://python.quantecon.org/pandas_panel.html), almost all python outputs are missing. For example, please see the following screenshot (left: PDFs generated by ``rst``, right: PDFs generated by ``myst``)

![Screen Shot 2021-02-11 at 8 44 12 am](https://user-images.githubusercontent.com/53931041/107576512-56383700-6c45-11eb-8559-007bd2064261.png)

**Comment by mmcky** [comment]
@shlff I suspect this is missing output due to support for `code-from-files` not being mainlined yet in `myst_nb`. So let's review this on the attached which is the latest build of the pdf from `fix-codefromfile` branch of this repo. 

[Uploading python.pdf…]()

**Comment by shlff** [comment]
Thanks @mmcky . Now I can confirm that all those missing python outputs are back in the latest PDF build you attached in the above comment.

**Comment by mmcky** [comment]
thanks @shlff
