### ISSUE TITLE
[jupyterbook-latex] [ols] error message in two python cells

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#97]
Hi @AakashGfude and @mmcky , I find that in the myst-PDF lecture [ols](https://quantecon.github.io/lecture-python.myst/ols.html),
- there are two python code cells with error messages, while their website versions do not have such error messages. 

For example, please see the screenshot (left: webpages generated by ``myst``, right: PDFs generated by ``myst``):
 
![Screen Shot 2021-02-11 at 8 58 50 am](https://user-images.githubusercontent.com/53931041/107578091-69e49d00-6c47-11eb-8169-8fd720c46269.png)

**Comment by mmcky** [comment]
This is fixed on the latest `pdf` built using `fix-codefromfile` branch. 

[python.pdf](https://github.com/QuantEcon/lecture-python.myst/files/5979422/python.pdf)

**Comment by shlff** [comment]
Thanks @mmcky . I checked the pdf you attached and this issue should have been solved using ``fix-codefromfile`` branch.

I will close this issue.

**Comment by AakashGfude** [comment]
@shlff actually still getting this error, from the latest code and environment. But the same error is there in HTML as well, so I think it has to do with the code and packages itself, rather then `jupyterbook-latex`.

**Comment by shlff** [comment]
Thanks @AakashGfude . I will check the code and packages again and discuss them with you soon.

**Comment by shlff** [comment]
Thanks @mmcky and @AakashGfude for your beautiful work. This is no longer an issue, so I will close it.
