### ISSUE TITLE
[jupyterbook-latex] some blank pages

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#99]
Hi @AakashGfude and @mmcky , I find that there are some blank pages (for example the following one). I am not so sure that they are necessary here and would love to hear your comments.

![Screen Shot 2021-02-11 at 9 05 05 am](https://user-images.githubusercontent.com/53931041/107578887-6ef61c00-6c48-11eb-8ac7-f1f373154ce9.png)

**Comment by mmcky** [comment]
I suspect the `bibliography` directive should just be contained in that `zreferences.md` file without a title perhaps?

**Comment by shlff** [comment]
Closed.
